In [ ]:
#| default_exp handlers.helcom

# HELCOM

> This data pipeline, known as a "handler" in Marisco terminology, is designed to clean, standardize, and encode [HELCOM data](https://helcom.fi/about-us) into `NetCDF` format. The handler processes raw HELCOM data, applying various transformations and lookups to align it with `MARIS` data standards.

Key functions of this handler:

- **Cleans** and **normalizes** raw HELCOM data
- **Applies standardized nomenclature** and units
- **Encodes the processed data** into `NetCDF` format compatible with MARIS requirements

This handler is a crucial component in the Marisco data processing workflow, ensuring HELCOM data is properly integrated into the MARIS database.

**[newer version in progress]**

::: {.callout-tip}
## Getting Started

- For new MARIS users, please refer to [Understanding MARIS Data Formats (NetCDF and Open Refine)](https://github.com/franckalbinet/marisco/blob/main/nbs/reference/field-definition.ipynb) for detailed information.
- For new HELCOM users, please refer to the [HELCOM Metadata Portal](https://metadata.helcom.fi/geonetwork/srv/fin/catalog.search#/metadata/2fdd2d46-0329-40e3-bf96-cb08c7206a24) for detailed information regarding the `GUIDELINES FOR MONITORING OF RADIOACTIVE SUBSTANCES`.

:::

The present notebook pretends to be an instance of [Literate Programming](https://www.wikiwand.com/en/articles/Literate_programming) in the sense that it is a narrative that includes code snippets that are interspersed with explanations. When a function or a class needs to be exported in a dedicated python module (in our case `marisco/handlers/helcom.py`) the code snippet is added to the module using `#| exports` as provided by the wonderful [nbdev](https://nbdev.readthedocs.io/en/latest/) library.

In [ ]:
#| hide
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:

  %reload_ext autoreload

In [ ]:
#| export
from fastcore.all import *
import pandas as pd
import numpy as np
import re

from marisco.configs import NA, NC_DTYPES, get_lut, lut_path, cache_path
from marisco.match import uniq_across_dfs, lut_from, fuzzy_merge, fix_lut, make_lut, make_lut_from
from marisco.geo import ddmm_to_dd
from marisco.utils import ExtractNetcdfContents
from marisco.callbacks import (
    Callback, PerGroupCB, Transformer,
    EncodeTimeCB, LowerStripNameCB, SanitizeLonLatCB,
    CompareDfsAndTfmCB, RemapCB)
from marisco.metadata import GlobAttrsFeeder, BboxCB, DepthRangeCB, TimeRangeCB, ZoteroCB, KeyValuePairCB
from marisco.encoders import NetCDFEncoder
from marisco.netcdf2csv import decode

import warnings
warnings.filterwarnings('ignore')

In [ ]:
#| hide
pd.set_option('display.max_rows', 100)

## Configuration & file paths

- **src_dir**: path to the [maris-crawlers](https://github.com/franckalbinet/maris-crawlers) folder containing the HELCOM data in CSV format.

- **fname_out**: path and filename for the NetCDF output.The path can be defined as a relative path. 

- **Zotero key**: used to retrieve attributes related to the dataset from [Zotero](https://www.zotero.org/). The MARIS datasets include a [library](https://maris.iaea.org/datasets) available on [Zotero](https://www.zotero.org/groups/2432820/maris/library).

In [ ]:
#| exports
src_dir = 'https://raw.githubusercontent.com/franckalbinet/maris-crawlers/refs/heads/main/data/processed/HELCOM%20MORS'
fname_out = '../../_data/output/100-HELCOM-MORS-2024.nc'
zotero_key ='26VMZZ2Q' # HELCOM MORS zotero key

## Load data

[Helcom MORS (Monitoring of Radioactive Substances in the Baltic Sea) data](https://helcom.fi/about-us) is provided as a zipped Microsoft Access database. We automatically fetch and convert this dataset with database tables exported as `.csv` files using a Github action here: [maris-crawlers](https://github.com/franckalbinet/maris-crawlers/blob/main/.github/workflows/fetch-data-sources.yml). 

The dataset is then accessible in an amenable format for the `marisco` data pipeline.

In [ ]:
#| exports
default_smp_types = {  
    'BIO': 'BIOTA', 
    'SEA': 'SEAWATER', 
    'SED': 'SEDIMENT'
}

In [ ]:
#| export
def load_data(fname_in):
    "Load HELCOM data; returns dict of DataFrames keyed by sample type."
    res = {}
    for prefix,smp_type in default_smp_types.items():
        smp = pd.read_csv(f'{fname_in}/{prefix}01.csv').rename(str.lower, axis='columns')
        meas = pd.read_csv(f'{fname_in}/{prefix}02.csv').rename(str.lower, axis='columns')
        res[smp_type] = smp.merge(meas, on='key')
    return res

`dfs` is a dictionary of dataframes created from the Helcom dataset located at the path `src_dir`. The data to be included in each dataframe is sorted by sample type. Each dictionary is defined with a key equal to the sample type.

In [ ]:
#| eval: false
dfs = load_data(src_dir)
test_eq(list(dfs.keys()), ['BIOTA', 'SEAWATER', 'SEDIMENT'])

In [ ]:
#| eval: false
for k,v in dfs.items():
    print(f"{k}: {v.shape[0]} rows, {v.shape[1]} cols")
    print(v.columns.tolist(), '\n')

BIOTA: 16124 rows, 33 cols

['key', 'country', 'laboratory', 'sequence', 'date', 'year', 'month', 'day', 'station', 'latitude ddmmmm', 'latitude dddddd', 'longitude ddmmmm', 'longitude dddddd', 'sdepth', 'rubin', 'biotatype', 'tissue', 'no', 'length', 'weight', 'dw%', 'loi%', 'mors_subbasin', 'helcom_subbasin', 'date_of_entry_x', 'nuclide', 'method', '< value_bq/kg', 'value_bq/kg', 'basis', 'error%', 'number', 'date_of_entry_y']

SEAWATER: 21626 rows, 27 cols

['key', 'country', 'laboratory', 'sequence', 'date', 'year', 'month', 'day', 'station', 'latitude (ddmmmm)', 'latitude (dddddd)', 'longitude (ddmmmm)', 'longitude (dddddd)', 'tdepth', 'sdepth', 'salin', 'ttemp', 'filt', 'mors_subbasin', 'helcom_subbasin', 'date_of_entry_x', 'nuclide', 'method', '< value_bq/m³', 'value_bq/m³', 'error%_m³', 'date_of_entry_y']

SEDIMENT: 40743 rows, 35 cols

['key', 'country', 'laboratory', 'sequence', 'date', 'year', 'month', 'day', 'station', 'latitude (ddmmmm)', 'latitude (dddddd)', 'longitude (ddmmmm)', 'longitude (dddddd)', 'device', 'tdepth', 'uppsli', 'lowsli', 'area', 'sedi', 'oxic', 'dw%', 'loi%', 'mors_subbasin', 'helcom_subbasin', 'sum_link', 'date_of_entry_x', 'nuclide', 'method', '< value_bq/kg', 'value_bq/kg', 'error%_kg', '< value_bq/m²', 'value_bq/m²', 'error%_m²', 'date_of_entry_y']

## Normalize nuclide names

### Fix trailing spaces

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER
Trailing whitespace in nuclide names: ~325 rows across the dataset contain nuclide values with one or more trailing spaces (e.g. 'PU238 ', 'CS137 ', 'SR90 '). These should be trimmed at source.
:::

For instance, rows where the raw nuclide name has trailing whitespace:

In [ ]:
#| eval: false
bad = pd.concat(dfs.values(), ignore_index=True).query('nuclide != nuclide.str.strip()')
print(f"{len(bad)} rows with trailing spaces. Examples:\n")
print(bad.drop_duplicates('nuclide')['nuclide'].to_list()[:8])

325 rows with trailing spaces. Examples:

['PU238   ', 'AM241   ', 'CS137    ', 'CS137   ', 'CS134   ', 'CO60    ', 'K40     ', 'SR90    ']

`LowerStripNameCB` lowercases and strips them into a standardised `NUCLIDE` column.

In [ ]:
#| eval: false
tfm = Transformer(dfs, cbs=[LowerStripNameCB(col_src='nuclide', col_dst='NUCLIDE')])
tfm()

for df in tfm.dfs.values():
    test_eq(df['NUCLIDE'], df['NUCLIDE'].str.lower().str.strip())
print(f"All nuclide names normalised across {len(tfm.dfs)} sample groups.")

All nuclide names normalised across 3 sample groups.

### Align nuclide names with MARIS

HELCOM nuclide names are lowercased and stripped by `LowerStripNameCB` above, but some names need expert overrides: combined totals like `cs134137` (caesium-134+137 sum, maps to `cs134_137_tot`), compound codes like `cm243244` (curium-243+244), and clearly-as-typos like `cs143` (likely cs137). We reconcile these by following the same semi-automated workflow used across marisco handlers: 

1. get familiar with the provider's codes, 
2. try an automatic mapping, 
3. fix what it got wrong, 
4. and check the result.

We derive the unique nuclide values from the data after lowercase/normalisation, then fuzzy‑match them against the MARIS nuclide reference table.

In [ ]:
#| eval: false
tfm = Transformer(dfs, cbs=[LowerStripNameCB(col_src='nuclide', col_dst='NUCLIDE')])

**Try an automatic mapping**

*Derive unique provider values and fuzzy-match against MARIS reference.*

In [ ]:
#| eval: false
provider_lut = lut_from(tfm(), 'NUCLIDE')
maris_ref = get_lut('NUCLIDE', as_df=True)

print("provider_lut:", provider_lut.columns.tolist())
print("maris_ref:   ", maris_ref.columns.tolist())

merged = fuzzy_merge(provider_lut, maris_ref, left_on='value', right_on='nc_name')

provider_lut: ['value']

maris_ref:    ['nuclide_id', 'nc_name']

**Inspect the borderline matches**

*Review non-exact matches to identify cases the fuzzy matcher could not resolve.*

In [ ]:
#| eval: false
# Entries with score > 0 need human review
non_exact = merged[merged.score > 0].sort_values('score', ascending=False)
print(non_exact)

       value  nuclide_id nc_name  score
12  cm243244          73   cm242      3
18  cs134137          31   cs134      3
49  pu239240          68   pu239      3
47  pu238240          67   pu238      3
25     cs143           3     c14      2
24     cs142           3     c14      2
27     cs145           3     c14      2
22     cs140         129   ce140      1
21     cs139          31   cs134      1
20     cs138          31   cs134      1
23     cs141          36   ce141      1
26     cs144          31   cs134      1
36      k-40           4     k40      1
28     cs146         102   cs136      1

The table above shows the borderline cases. Some are legitimate combined-total nuclides (`cs134137`, `cm243244`, `pu239240`, `pu238240`) that should map to their MARIS `_tot` counterparts. Others are typos or historical artefacts — e.g. `cs143`, `cs145`, `cs142`, `cs141`, `cs144`, `cs140`, `cs146`, `cs139`, `cs138` are all clearly variants of cs137. `k-40` is simply k40 with a hyphen. These overrides are captured below.

**Fix what it got wrong**

*Apply expert overrides for cases the fuzzy match could not resolve correctly.*

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER
**Inconsistent nuclide naming conventions** — Most nuclide names follow the standard alphanumeric format (e.g. `cs137`, `k40`), but a few entries are inconsistent:
- `k-40` uses a hyphen, unlike other entries (should be `k40`)
- A cluster of entries (`cs140`–`cs146`, `cs138`, `cs139`) appear to be typos for `cs137`

A standardised nuclide pick-list at the point of entry would prevent these issues.

:::

In [ ]:
#| exports
fixes_nuclide_names = {
    'cs134137': 'cs134_137_tot',
    'cm243244': 'cm243_244_tot',
    'pu239240': 'pu239_240_tot',
    'pu238240': 'pu238_240_tot',
    'cs143': 'cs137',
    'cs145': 'cs137',
    'cs142': 'cs137',
    'cs141': 'cs137',
    'cs144': 'cs137',
    'k-40': 'k40',
    'cs140': 'cs137',
    'cs146': 'cs137',
    'cs139': 'cs137',
    'cs138': 'cs137'
    }

The dictionary below records our expert decisions for every case the fuzzy matcher got wrong. Each entry maps a provider nuclide value to its correct MARIS `nc_name`. The `fix_lut` function applies these overrides and resets the score to 0.

In [ ]:
fixed = fix_lut(merged, fixes_nuclide_names, maris_ref,
                left_on='value', right_on='nc_name', id_col='nuclide_id')

# Verify: no unresolved matches remain
unresolved = fixed[fixed['score'] > 0]
print(unresolved if len(unresolved) else "All nuclide entries resolved. ✓")

All nuclide entries resolved. ✓

**Assemble the final mapping**

The four steps above (unique values, fuzzy match, expert overrides, verification) told us what the correct MARIS translations are. The `make_lut` function packages that knowledge, the expert fixes and the MARIS reference table, into a single function that the Transformer can call later, when it is processing the data through the pipeline.

In [ ]:
#| exports
# Resolved nuclide lookup table (provider → MARIS nuclide_id); lazy, resolves at Transformer time
nuclide_lut = make_lut('NUCLIDE', fixes=fixes_nuclide_names)

The `nuclide_lut` lookup table is passed to the generic `RemapCB` callback, which looks up the MARIS nuclide reference table behind the scenes when the Transformer runs. The mapping translates `NUCLIDE` (the provider string after lowercasing and stripping) into `NUCLIDE` (the MARIS integer nuclide_id) across all sample-type groups.

Let's verify the full pipeline works:

In [ ]:
#| eval: false
tfm = Transformer(dfs, cbs=[
    LowerStripNameCB(col_src='nuclide', col_dst='NUCLIDE'),
    RemapCB(lut=nuclide_lut, col_remap='NUCLIDE', col_src='NUCLIDE')
    ])
    
dfs_out = tfm()

In [ ]:
#| eval: false
print(f"NUCLIDE is integer MARIS IDs in all {len(dfs_out)} groups. ✓")
for key in dfs_out.keys():
    test_eq(dfs_out[key]['NUCLIDE'].dtype, 'int64')

NUCLIDE is integer MARIS IDs in all 3 groups. ✓

A quick sanity check confirms that the expert-mapped nuclides like cs134_137_tot and cs137 are properly assigned to actual rows in the output:

In [ ]:
#| eval: false
for name, ncid in [('cs134_137_tot', 76), ('cs137', 33)]:
    n = (dfs_out['BIOTA'].NUCLIDE == ncid).sum()
    print(f"{name} (id={ncid}): {n} rows")
    test_ne(n, 0)

cs134_137_tot (id=76): 91 rows

cs137 (id=33): 4610 rows

## Standardize time

HELCOM provides dates in a `DATE` column (format `MM/DD/YY HH:MM:SS`), but ~1,500 rows across the dataset have missing `DATE` values. The raw data also includes separate `YEAR`, `MONTH`, `DAY` columns as fallback, though some rows have `MONTH=0` or `DAY=0` (unknown), which we set to 1.

`ParseTimeCB` handles this in three steps: it parses the `DATE` column using pandas, replaces `MONTH=0` / `DAY=0` with 1, and fills any remaining missing `TIME` values by constructing dates from the `YEAR`/`MONTH`/`DAY` columns.

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER

Time/date is provided in `DATE`, `YEAR`, `MONTH`, and `DAY` columns. The `DATE` column contains ~1,500 missing values across the dataset. These should ideally be populated at source. Additionally, `MONTH=0` or `DAY=0` occurs when the day or month is unknown; we set these to 1 as a convention, but a standardised sentinel value for unknown components would be clearer.
:::

In [ ]:
#| eval: false
# Show rows with missing or zero date components in SEAWATER
df = dfs['SEAWATER']
bad_dates = df[df['date'].isna()]
bad_parts  = df[(df['day'] == 0) | (df['month'] == 0)]

print(f"Missing DATE values: {len(bad_dates)} rows")
print(f"Zero day or month:  {len(bad_parts)} rows")
print(bad_dates[['date','year','month','day']].head(3))

Missing DATE values: 546 rows

Zero day or month:  107 rows

      date  year  month  day
11332  NaN  2013      6  3.0
11333  NaN  2013      6  3.0
11334  NaN  2013      6  3.0

In [ ]:
#| export
class ParseTimeCB(PerGroupCB):
    "Parse HELCOM DATE (MM/DD/YY HH:MM:SS) with fallback to YEAR/MONTH/DAY."
    def each_grp(self, grp, df, tfm):
        df['TIME'] = pd.to_datetime(df['date'], format='%m/%d/%y %H:%M:%S', errors='coerce')
        for c in ['day','month']: df.loc[df[c]==0,c] = 1
        m = df['TIME'].isna()
        df.loc[m,'TIME'] = pd.to_datetime(df.loc[m, ['year','month','day']], errors='coerce')

Applying `ParseTimeCB` across all sample-type groups:

In [ ]:
#| eval: false
tfm = Transformer(dfs, cbs=[ParseTimeCB()])
dfs_out = tfm()

print(f"TIME column added across {len(dfs_out)} groups. ✓")
print(dfs_out['SEAWATER'][['TIME']].head(3))
test_eq('TIME' in dfs_out['SEAWATER'].columns, True)
test_eq(dfs_out['SEAWATER']['TIME'].isna().sum(), 0)

TIME column added across 3 groups. ✓

        TIME
0 1984-06-13
1 1984-06-13
2 1984-06-13

NetCDF stores time as milliseconds since an origin (here `1970-01-01`, as defined in the template's CDL). `EncodeTimeCB` converts the parsed `TIME` column to this integer format; rows with unresolvable dates are dropped (8 in SEAWATER, 1 in SEDIMENT).

Applying `ParseTimeCB` and `EncodeTimeCB` together:

In [ ]:
#| eval: false
tfm = Transformer(dfs, cbs=[ParseTimeCB(), EncodeTimeCB()])
dfs_out = tfm()

print(f"TIME encoded as int64 in all {len(dfs_out)} groups. ✓")
test_eq(dfs_out['SEAWATER']['TIME'].dtype, 'int64')
test_eq(dfs_out['SEAWATER']['TIME'].isna().sum(), 0)

Warning: 6 missing time value(s) in BIOTA

TIME encoded as int64 in all 3 groups. ✓

## Melt sediment values

HELCOM sediment records are in wide format: each row carries two parallel measurement columns (`VALUE_Bq/kg` and `value_bq/m²`, plus their associated uncertainty and detection-limit columns). MARIS expects tidy/long format; one measurement per row with a UNIT code identifying the original column. So we unpivot (melt) the sediment data, creating separate rows for each measurement type.

To make the transformation explicit: the melt copies values from each measurement-type group into columns prefixed with `_` (`_VALUE`, `_UNC`, `_DL`, `_UNIT`). The underscore marks these as intermediate; they will be renamed to their final MARIS-standard column names in a later step.

:::{.callout-note}
## Feedback to data provider
**Tidy/long format would simplify ingestion.** HELCOM supplies sediment measurements in wide format (Bq/kg and Bq/m² columns on the same row). MARIS expects one measurement per row with a unit identifier. This means every sediment row with data in both columns must be split into two rows during ingestion, an extra transformation step that a long-format delivery would avoid.
:::

In [ ]:
# Let's see what the sediment data looks like and why we need to split
sed = dfs['SEDIMENT']

cols = ['key','nuclide','value_bq/kg','< value_bq/kg','error%_kg','value_bq/m²','< value_bq/m²','error%_m²']
print("Random sample of 3 sediment rows:")
print(sed[cols].sample(3).to_string(index=False), '\n')

# How many rows have data in BOTH columns?
both = sed[sed['value_bq/kg'].notna() & sed['value_bq/m²'].notna()]
print(f"Rows with values in BOTH Bq/kg and Bq/m²: {len(both):,} out of {len(sed):,} ({100*len(both)/len(sed):.0f}%)")

Random sample of 3 sediment rows:

         key nuclide  value_bq/kg < value_bq/kg  error%_kg  value_bq/m² < value_bq/m²  error%_m²
SSAAS1988017     K40      700.000           NaN       11.0          NaN           NaN        NaN
SRISO2011020   TH232       21.473           NaN       15.0       330.00           NaN        NaN
SDHIG2013155     K40      512.800           NaN        0.8     10762.17           NaN        NaN

Rows with values in BOTH Bq/kg and Bq/m²: 29,926 out of 40,743 (73%)

The mapping below defines which raw columns correspond to `VALUE`, uncertainty (`UNC`), and detection limit (`DL`) for each measurement type, together with the MARIS unit ID to assign.

In [ ]:
#| exports
# Column mappings per sediment measurement type: MARIS-standard column name → raw HELCOM column name
coi_sediment = {
    'kg_type': {
        'VALUE': 'value_bq/kg',  # Activity concentration per unit mass
        'UNC': 'error%_kg',      # Relative uncertainty (percent)
        'DL': '< value_bq/kg',   # Detection limit flag/level
        'UNIT': 3,               # Unit ID for Bq/kg
    },
    'm2_type': {
        'VALUE': 'value_bq/m²',  # Activity per unit area
        'UNC': 'error%_m²',      # Relative uncertainty (percent)
        'DL': '< value_bq/m²',   # Detection limit flag/level
        'UNIT': 2,               # Unit ID for Bq/m²
    }
}

`SplitSedimentValuesCB` reads each measurement-type group from the mapping above, checks which rows have data in that group's `VALUE`/`UNC`/`DL` columns, and copies those values into a standard set of temporary columns prefixed with `_`. It then concatenates all measurement-type subsets into a single sediment dataframe. The underscore prefix marks these columns as intermediate (they will be finally renamed in a later step).

In [ ]:
#| export
class MeltSedimentValuesCB(PerGroupCB):
    "Melt HELCOM dual-value sediment rows into separate rows per measurement type (Bq/kg, Bq/m²)."
    grps = ['SEDIMENT']
    def __init__(self, coi:dict  # Column-of-interest mapping, keyed by unit variant (kg, m²)
            ): store_attr()

    def each_grp(self, grp, df, tfm):
        parts = []
        for cols in self.coi.values():
            sel = df[[cols[v] for v in ['VALUE','UNC','DL']]].notna().any(axis=1)
            if not sel.any(): continue
            parts.append(df[sel].rename(columns={
                cols['VALUE']:'_VALUE', cols['UNC']:'_UNC',
                cols['DL']:'_DL'}).assign(_UNIT=cols['UNIT']))
        if parts: tfm.dfs[grp] = pd.concat(parts, ignore_index=True)

In [ ]:
#| eval: false
tfm = Transformer(dfs, cbs=[MeltSedimentValuesCB(coi_sediment)])
dfs_out = tfm()

print(f"SEDIMENT rows: {dfs['SEDIMENT'].shape[0]} → {dfs_out['SEDIMENT'].shape[0]} after melt")
test_eq('_VALUE' in dfs_out['SEDIMENT'].columns, True)
test_eq('_UNIT' in dfs_out['SEDIMENT'].columns, True)
test_eq(dfs_out['SEDIMENT']['_UNIT'].isin([2, 3]).all(), True)

SEDIMENT rows: 40743 → 70695 after melt

## Sanitize value

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER

Some of the HELCOM datasets contain missing values in the `VALUE` column, see output after applying the `SanitizeValueCB` callback.

:::

HELCOM measurement values live in differently named columns depending on the sample type — `value_bq/m³` for seawater, `value_bq/kg` for biota, and `_VALUE` for sediment (created by the previous melt step). `SanitizeValueCB` collects these into a single `VALUE` column and drops rows that lack a measurement value, since MARIS requires a non-null measurement for every record.

In [ ]:
#| exports
coi_val = {'SEAWATER' : {'VALUE': 'value_bq/m³'},
           'BIOTA':  {'VALUE': 'value_bq/kg'},
           'SEDIMENT': {'VALUE': '_VALUE'}}

In [ ]:
#| export
class SanitizeValueCB(PerGroupCB):
    "Sanitize measurement values by removing blanks and standardizing to use the `VALUE` column."
    def __init__(self,
                 coi: Dict[str, Dict[str, str]], # Columns of interest. Format: {group_name: {'VALUE': 'column_name'}}
                 ):
        store_attr()

    def each_grp(self, grp, df, tfm):
        value_col = self.coi[grp]['VALUE']
        tfm.dfs[grp] = df.dropna(subset=[value_col])
        tfm.dfs[grp]['VALUE'] = tfm.dfs[grp][value_col]

In [ ]:
#| eval: false
tfm = Transformer(dfs, cbs=[MeltSedimentValuesCB(coi_sediment),
                            SanitizeValueCB(coi_val),
                            ])
dfs_out = tfm()

print(f"VALUE column created across all {len(dfs_out)} groups.")
for key in dfs_out.keys():
    test_eq('VALUE' in dfs_out[key].columns, True)
    test_eq(dfs_out[key]['VALUE'].isna().sum(), 0)

VALUE column created across all 3 groups.

## Normalize uncertainty

HELCOM provides measurement uncertainty as a relative percentage, but MARIS requires absolute (standard) uncertainty. The percentage column also has a different name in each sample group (`error%_m³` for seawater, `error%` for biota, `_UNC` for sediment). `NormalizeUncCB` converts each group's percentage column to an absolute `UNC` column by multiplying the percentage by the measured value.

In [ ]:
coi_units_unc = {
    'SEAWATER': ('VALUE', 'error%_m³'),
    'BIOTA':    ('VALUE', 'error%'),
    'SEDIMENT': ('VALUE', '_UNC'),
}

In [ ]:
class NormalizeUncCB(PerGroupCB):
    "Convert relative uncertainty (percent) to absolute (standard) uncertainty per group."
    def __init__(self,
                 coi: dict=coi_units_unc,  # {group: (meas_col, unc_col)}
                ):
        store_attr()

    def each_grp(self, grp, df, tfm):
        if grp not in self.coi: return
        meas_col, unc_col = self.coi[grp]
        df['UNC'] = df[unc_col] * df[meas_col] / 100

Run `NormalizeUncCB` on mock data from all three groups. The output confirms the conversion produces the expected absolute uncertainties. The assertions below verify the arithmetic inline.

In [ ]:
#| eval: false
tfm = Transformer(dfs, cbs=[
    MeltSedimentValuesCB(coi_sediment), 
    SanitizeValueCB(coi_val),
    NormalizeUncCB()])

tfm()['SEDIMENT'][['VALUE', 'UNC', '_UNIT']].head()

   VALUE    UNC  _UNIT
0   32.0  0.960      3
1   32.0  3.200      3
2   29.0  3.190      3
3    5.5  1.760      3
4    6.4  1.792      3

In [ ]:
# Verify NormalizeUncCB computes correctly on mock data
dfs_mock = {
    'SEAWATER': pd.DataFrame({'VALUE': [5.3, 19.9], 'error%_m³': [32.0, 20.0]}),
    'BIOTA':    pd.DataFrame({'VALUE': [135.3],     'error%':    [3.57]}),
    'SEDIMENT': pd.DataFrame({'VALUE': [1200.0, 250.0], '_UNC': [20.0, 20.0]}),
}
tfm = Transformer(dfs_mock, cbs=[NormalizeUncCB()])
tfm()

{'SEAWATER':    VALUE  error%_m³    UNC
 0    5.3       32.0  1.696
 1   19.9       20.0  3.980,
 'BIOTA':    VALUE  error%      UNC
 0  135.3    3.57  4.83021,
 'SEDIMENT':     VALUE  _UNC    UNC
 0  1200.0  20.0  240.0
 1   250.0  20.0   50.0}

In [ ]:
test_eq(tfm.dfs['SEAWATER']['UNC'].to_list(), [5.3*32/100, 19.9*20/100])
test_eq(tfm.dfs['BIOTA']['UNC'].to_list(),    [135.3*3.57/100])
test_eq(tfm.dfs['SEDIMENT']['UNC'].to_list(), [1200.0*20/100, 250.0*20/100])
print("NormalizeUncCB on mock data: all assertions passed. ✓")

NormalizeUncCB on mock data: all assertions passed. ✓

## Remap units

HELCOM encodes units differently per sample type. SEAWATER uses Bq/m³ (implied by the column name `value_bq/m³`). BIOTA uses Bq/kg with a `basis` column distinguishing wet weight (W), dry weight (D), or fresh weight (F). SEDIMENT gets its unit from the melt step's `_UNIT` column (Bq/kg or Bq/m²). `RemapUnitCB` collects these into a single MARIS-standard `UNIT` column.

For the `BIOTA` sample type, the base unit is `Bq/kg`, as indicated in the `value_bq/kg` column. The distinction between wet (W) and dry weight (D) is specified in the basis column.

In [ ]:
#| eval: false
dfs['BIOTA'][['value_bq/kg', 'basis']].head(1)

   value_bq/kg basis
0      0.00816     W

For the `SEAWATER` sample type, the unit is `Bq/m³` as indicated in the `value_bq/m³` column.

In [ ]:
#| eval: false
dfs['SEAWATER'][['value_bq/m³']].head(1)

   value_bq/m³
0          6.7

We can now review the units that are available in MARIS:

In [ ]:
#| eval: false
print(get_lut('UNIT', as_df=True))

    unit_id  unit_sanitized
0        -1  Not applicable
1         0   NOT AVAILABLE
2         1       Bq per m3
3         2       Bq per m2
4         3       Bq per kg
5         4      Bq per kgd
6         5      Bq per kgw
7         6       kg per kg
8         7              TU
9         8  DELTA per mill
10        9     atom per kg
11       10    atom per kgd
12       11    atom per kgw
13       12      atom per l
14       13      Bq per kgC

We define unit renaming rules for HELCOM in an **ad hoc** way:

In [ ]:
#| exports
lut_units = {
    'SEAWATER': 1,  # 'Bq/m3'
    'SEDIMENT': '_UNIT',  # Accounted for in MeltSedimentValuesCB
    'BIOTA': {
        'D': 4,  # 'Bq/kgd'
        'W': 5,  # 'Bq/kgw'
        'F': 5   # 'Bq/kgw' (fresh assumed = wet)
    }
}

We define the `RemapUnitCB` callback to set the `UNIT` column in the DataFrames based on the lookup table `lut_units`.

In [ ]:
#| export
#| exports
class RemapUnitCB(PerGroupCB):
    "Set the MARIS-standard UNIT column from per-sample-type conventions (column name, basis column, or melt result)."
    def __init__(self,
                 lut_units: dict=lut_units  # Per-group unit mapping: group -> literal ID or {basis_code -> ID}
                ):
        store_attr()

    def each_grp(self, grp, df, tfm):
        if grp == 'SEAWATER': df['UNIT'] = self.lut_units[grp]
        elif grp == 'BIOTA': df['UNIT'] = df['basis'].apply(lambda x: self.lut_units[grp].get(x, 0))
        elif grp == 'SEDIMENT': df['UNIT'] = df['_UNIT']

A quick sanity check on mock data confirms the callback assigns the correct UNIT IDs for every sample type. SEAWATER always gets unit 1 (Bq/m³). BIOTA rows get 4 for dry weight, 5 for wet/fresh weight, and 0 for unknown basis codes. SEDIMENT picks up whatever `_UNIT` the melt step assigned, either 2 (Bq/m²) or 3 (Bq/kg):

In [ ]:
# Verify RemapUnitCB assigns correct UNIT IDs on mock data
dfs_mock = {
    'SEAWATER': pd.DataFrame({'dummy': [1, 2]}),
    'BIOTA':    pd.DataFrame({'basis': ['D', 'W', 'F', 'X']}),
    'SEDIMENT': pd.DataFrame({'_UNIT': [2, 3, 2]}),
}
tfm = Transformer(dfs_mock, cbs=[RemapUnitCB()])
tfm()

test_eq(tfm.dfs['SEAWATER']['UNIT'].to_list(), [1, 1])
test_eq(tfm.dfs['BIOTA']['UNIT'].to_list(),   [4, 5, 5, 0])
test_eq(tfm.dfs['SEDIMENT']['UNIT'].to_list(), [2, 3, 2])
print("RemapUnitCB on mock data: all assertions passed. ✓")

RemapUnitCB on mock data: all assertions passed. ✓

Apply the transformer for callback `RemapUnitCB()`. Then, print the unique `UNIT` for the `SEAWATER` dataframe.

In [ ]:
#| eval: false
tfm = Transformer(dfs, cbs=[
                            SplitSedimentValuesCB(coi_sediment),
                            SanitizeValueCB(coi_val),
                            NormalizeUncCB(),
                            RemapUnitCB()
                            ])

tfm()
print(pd.DataFrame.from_dict(tfm.compare_stats) , '\n')

for grp in ['BIOTA', 'SEDIMENT', 'SEAWATER']:
    print(f"{grp}: {tfm()[grp]['UNIT'].unique()}")

NameError: name 'SplitSedimentValuesCB' is not defined

Running the full pipeline up to this point on the real HELCOM data confirms the units are assigned correctly across all sample-type groups:

In [ ]:
tfm = Transformer(dfs, cbs=[
    MeltSedimentValuesCB(coi_sediment),
    SanitizeValueCB(coi_val),
    NormalizeUncCB(),
    RemapUnitCB(),
])
dfs_out = tfm()

for grp in ['SEAWATER', 'BIOTA', 'SEDIMENT']:
    print(f"{grp}: UNIT values = {dfs_out[grp]['UNIT'].unique()}")

test_eq(set(dfs_out['SEAWATER']['UNIT'].unique()), {1})
test_eq(set(dfs_out['SEDIMENT']['UNIT'].unique()), {2, 3})
test_eq(set(dfs_out['BIOTA']['UNIT'].unique()), {0, 4, 5})

SEAWATER: UNIT values = [1]

BIOTA: UNIT values = [5 4 0]

SEDIMENT: UNIT values = [3 2]

## Remap detection limit

HELCOM encodes detection limits in provider-specific columns: `< value_bq/m³` for seawater, `< value_bq/kg` for biota, and `_DL` for sediment after the melt step (see [Melt sediment values](#melt-sediment-values)). When the raw column contains `<`, the measurement is a detection limit; otherwise it is a detected value. MARIS uses the following integer codes for this distinction:

In [ ]:
#| eval: false
print(get_lut('DL', as_df=True))

   id   name_sanitized
0  -1   Not applicable
1   0    Not available
2   1   Detected value
3   2  Detection limit
4   3     Not detected
5   4          Derived

The `coi_dl` mapping below specifies which raw column holds the detection-limit information for each sample group. `RemapDetectionLimitCB` converts these to the MARIS-standard `DL` column, assigning code `2` for detection limits (where the raw value is `<`) and `1` for detected values.

In [ ]:
#| exports
coi_dl = {'SEAWATER' : {'DL' : '< value_bq/m³'},
          'BIOTA':  {'DL' : '< value_bq/kg'},
          'SEDIMENT': {'DL' : '_DL'}}

In [ ]:
#| export
class RemapDetectionLimitCB(PerGroupCB):
    "Map HELCOM `<` / detected-value conventions to MARIS detection-limit integer codes (2 for DL, 1 for detected)."
    def __init__(self, 
                 coi: dict,  # Dict of column hosting the detection limit info for each sample type
                ):
        store_attr()
        
    def each_grp(self, grp, df, tfm):
        dl = self.coi[grp]['DL']
        df['DL'] = df[dl].apply(lambda x: 2 if x == '<' else 1)

In [ ]:
# Verify RemapDetectionLimitCB assigns correct DL codes on mock data
dfs_mock = {
    'SEAWATER': pd.DataFrame({'< value_bq/m³': ['<', '=', '<', None]}),
    'BIOTA':    pd.DataFrame({'< value_bq/kg': ['<', None, '=', '<']}),
    'SEDIMENT': pd.DataFrame({'_DL': ['=', None, '<', '<']}),
}
tfm = Transformer(dfs_mock, cbs=[RemapDetectionLimitCB(coi_dl)])
tfm()

test_eq(tfm.dfs['SEAWATER']['DL'].to_list(), [2, 1, 2, 1])
test_eq(tfm.dfs['BIOTA']['DL'].to_list(),    [2, 1, 1, 2])
test_eq(tfm.dfs['SEDIMENT']['DL'].to_list(), [1, 1, 2, 2])
print("RemapDetectionLimitCB on mock data: all assertions passed. ✓")

RemapDetectionLimitCB on mock data: all assertions passed. ✓

Running the full pipeline up to this point on the real HELCOM data confirms that every sample-type group gets the correct detection-limit codes:

In [ ]:
#| eval: false
tfm = Transformer(dfs, cbs=[
    MeltSedimentValuesCB(coi_sediment),
    SanitizeValueCB(coi_val),
    NormalizeUncCB(),
    RemapUnitCB(),
    RemapDetectionLimitCB(coi_dl),
])
dfs_out = tfm()

for grp in ['SEAWATER', 'BIOTA', 'SEDIMENT']:
    print(f"{grp}: DL values = {dfs_out[grp]['DL'].unique()}")

test_eq(set(dfs_out['SEAWATER']['DL'].unique()), {1, 2})
test_eq(set(dfs_out['BIOTA']['DL'].unique()),   {1, 2})
test_eq(set(dfs_out['SEDIMENT']['DL'].unique()), {1, 2})

SEAWATER: DL values = [1 2]

BIOTA: DL values = [2 1]

SEDIMENT: DL values = [1 2]

## Remap Biota species

The HELCOM Biota dataset records species using HELCOM's RUBIN code system, which is documented in the accompanying `RUBIN_NAME.csv` lookup table. We align these scientific names with the MARIS species nomenclature following the same inspect-match-fix workflow used for nuclide names above. The mapping involves two steps: each RUBIN code is first looked up against the provider's nomenclature to get a scientific name, then that scientific name is mapped to a MARIS species_id via fuzzy matching and expert overrides.

**Try an automatic mapping**

*Read the provider's `RUBIN_NAME.csv` and derive unique scientific names, then fuzzy-match them against the MARIS species reference.*

**Inspect the borderline matches**

*Review non-exact matches to identify cases the fuzzy matcher could not resolve.*

**Fix what it got wrong**

*Apply expert overrides for cases the fuzzy match could not resolve correctly.*

**Assemble the final mapping**

*Package the results into a lookup function the Transformer can call later.*

In [ ]:
#| exports
provider_lut_species = pd.read_csv(f'{src_dir}/RUBIN_NAME.csv')
print(provider_lut_species.head())

   RUBIN_ID     RUBIN    SCIENTIFIC NAME     ENGLISH NAME
0        11  ABRA BRA      ABRAMIS BRAMA            BREAM
1        12  ANGU ANG  ANGUILLA ANGUILLA              EEL
2        13  ARCT ISL  ARCTICA ISLANDICA   ISLAND CYPRINE
3        14  ASTE RUB    ASTERIAS RUBENS  COMMON STARFISH
4        15  CARD EDU      CARDIUM EDULE           COCKLE

In [ ]:
#| exports
provider_lut_tissues = pd.read_csv(f'{src_dir}/TISSUE.csv')
print(provider_lut_tissues.head())

   TISSUE                    TISSUE_DESCRIPTION
0       1                            WHOLE FISH
1       2           WHOLE FISH WITHOUT ENTRAILS
2       3  WHOLE FISH WITHOUT HEAD AND ENTRAILS
3       4                      FLESH WITH BONES
4       5          FLESH WITHOUT BONES (FILETS)

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER

Some `rubin` codes in the HELCOM Biota dataset do not appear in the `RUBIN_NAME.csv` lookup table. This includes entries with trailing spaces (`FUCU VES `, `GADU MOR  `) and apparently missing codes (`FUCU SPP`, `FURC LUMB`, `STUC PECT`). Trailing spaces should be trimmed at source, and any valid RUBIN codes missing from the lookup table should be added.
:::

In [ ]:
#| eval: false
set(dfs['BIOTA']['rubin']) - set(provider_lut_species['RUBIN'])

{'CHAR BALT', 'FUCU SPP', 'FUCU VES ', 'FURC LUMB', 'GADU MOR  ', 'STUC PECT'}

In [ ]:
#| eval: false
maris_ref = get_lut('SPECIES', as_df=True)
print(maris_ref.head())

   species_id                             species
0           0                       NOT AVAILABLE
1           1                 Aristeus antennatus
2           2                        Apostichopus
3           3  Saccharina japonica var. religiosa
4           4                  Siganus fuscescens

In [ ]:
#| eval: false
# Fuzzy-merge provider scientific names against MARIS species names
merged = fuzzy_merge(used_lut, maris_ref,
                     left_on='SCIENTIFIC NAME', right_on='species')

In [ ]:
#| eval: false
# Inspect non-exact matches
non_exact = merged[merged.score > 0].sort_values('score', ascending=False)
print(non_exact[['SCIENTIFIC NAME', 'species', 'score']].to_string())

            SCIENTIFIC NAME              species  score
39  STIZOSTEDION LUCIOPERCA    Sander lucioperca     10
20     LAMINARIA SACCHARINA   Laminaria japonica      7
6             CHARA BALTICA      Macoma balthica      6
4             CARDIUM EDULE            Cardiidae      6
11       ENCHINODERMATA CIM        Echinodermata      5
33            PSETTA MAXIMA      Pinctada maxima      5
22           MACOMA BALTICA      Macoma balthica      1
40      STUCKENIA PECTINATE  Stuckenia pectinata      1

In [ ]:
#| exports
fixes_species = {
    'LAMINARIA SACCHARINA': 'Saccharina latissima',
    'CARDIUM EDULE': 'Cerastoderma edule',
    'CHARA BALTICA': 'NOT AVAILABLE',
    'PSETTA MAXIMA': 'Scophthalmus maximus'
    }

In [ ]:
#| eval: false
fixed = fix_lut(merged, fixes_species, maris_ref,
                left_on='SCIENTIFIC NAME', right_on='species', id_col='species_id')

unresolved = fixed[fixed['score'] > 0]
print(unresolved[['SCIENTIFIC NAME', 'species']] if len(unresolved) else "All species entries resolved. ✓")

            SCIENTIFIC NAME              species
11       ENCHINODERMATA CIM        Echinodermata
22           MACOMA BALTICA      Macoma balthica
39  STIZOSTEDION LUCIOPERCA    Sander lucioperca
40      STUCKENIA PECTINATE  Stuckenia pectinata

Four entries (`ENCHINODERMATA CIM`, `MACOMA BALTICA`, `STIZOSTEDION LUCIOPERCA`, `STUCKENIA PECTINATE`) return non-zero fuzzy-match scores, but the matches are semantically correct: `Echinodermata`, `Macoma balthica`, `Sander lucioperca`, and `Stuckenia pectinata` are the right MARIS equivalents. No further overrides needed.

In [ ]:
#| exports
species_lut = make_lut_from(provider_lut_species, 'RUBIN', 'SCIENTIFIC NAME', 'SPECIES', fixes=fixes_species)

Verify species lookup on mock data:

In [ ]:
dfs_mock = {'BIOTA': pd.DataFrame({'rubin': ['ABRA BRA', 'CARD EDU', 'CHAR BALT']})}
tfm = Transformer(dfs_mock, cbs=[RemapCB(lut=species_lut, col_remap='SPECIES', col_src='rubin')])
tfm()
test_eq(tfm.dfs['BIOTA']['SPECIES'].to_list(), [271, 274, 0])

Map species on real HELCOM Biota data:

In [ ]:
#| eval: false
tfm = Transformer({'BIOTA': dfs['BIOTA'].copy()}, cbs=[
    LowerStripNameCB(col_src='nuclide', col_dst='NUCLIDE'),
    RemapCB(lut=species_lut, col_remap='SPECIES', col_src='rubin')
])
dfs_out = tfm()
test_eq(dfs_out['BIOTA']['SPECIES'].isna().sum(), 0)
test_eq(dfs_out['BIOTA']['SPECIES'].dtype, 'int64')
print(f"SPECIES mapped to integer MARIS IDs across {len(dfs_out['BIOTA'])} rows. ✓")

SPECIES mapped to integer MARIS IDs across 16124 rows. ✓

In [ ]:
#| eval: false
# Verify species mapping on real data
tfm = Transformer({'BIOTA': dfs['BIOTA'].copy()}, cbs=[
    LowerStripNameCB(col_src='nuclide', col_dst='NUCLIDE'),
    RemapCB(lut=species_lut, col_remap='SPECIES', col_src='rubin')
])
dfs_out = tfm()
test_eq(dfs_out['BIOTA']['SPECIES'].dtype, 'int64')
print(f"SPECIES mapped to integer MARIS IDs across {len(dfs_out['BIOTA'])} rows. \u2713")

SPECIES mapped to integer MARIS IDs across 16124 rows. ✓

## Remap Body Part

Biota tissue is recorded as HELCOM TISSUE codes documented in the accompanying `TISSUE.csv` lookup table. We reconcile these with the MARIS body-part nomenclature following the same inspect-match-fix workflow used for species above.

In [ ]:
#| eval: false
maris_ref = get_lut('BODY_PART', as_df=True)
print(maris_ref.head())

# Fuzzy-merge provider tissue descriptions against MARIS body-part names
merged = fuzzy_merge(provider_lut_tissues, maris_ref,
                     left_on='TISSUE_DESCRIPTION', right_on='bodypar')

   bodypar_id                                bodypar
0          -1                         Not applicable
1           0                        (Not available)
2           1                           Whole animal
3           2               Whole animal eviscerated
4           3  Whole animal eviscerated without head

In [ ]:
# Inspect non-exact matches
#| eval: false
non_exact = merged[merged.score > 0].sort_values('score', ascending=False)
print(non_exact[['TISSUE_DESCRIPTION', 'bodypar', 'score']].to_string())

                      TISSUE_DESCRIPTION                bodypar  score
2   WHOLE FISH WITHOUT HEAD AND ENTRAILS    Flesh without bones     20
1            WHOLE FISH WITHOUT ENTRAILS    Flesh without bones     13
7                         SKIN/EPIDERMIS               Skeleton     10
4           FLESH WITHOUT BONES (FILETS)    Flesh without bones      9
0                             WHOLE FISH           Whole animal      5
11                              ENTRAILS                  Brain      5
14                   STOMACH + INTESTINE  Stomach and intestine      3
21                         WHOLE ANIMALS           Whole animal      1

We address several entries that were not correctly matched, as detailed below:

In [ ]:
#| exports
fixes_biota_tissues = {
    'WHOLE FISH WITHOUT HEAD AND ENTRAILS': 'Whole animal eviscerated without head',
    'WHOLE FISH WITHOUT ENTRAILS': 'Whole animal eviscerated',
    'SKIN/EPIDERMIS': 'Skin',
    'ENTRAILS': 'Viscera'
    }

In [ ]:
#| eval: false
maris_ref = get_lut('BODY_PART', as_df=True)
fixed = fix_lut(merged, fixes_biota_tissues, maris_ref,
                left_on='TISSUE_DESCRIPTION', right_on='bodypar', id_col='bodypar_id')

unresolved = fixed[fixed['score'] > 0]
print(unresolved[['TISSUE_DESCRIPTION', 'bodypar']] if len(unresolved) else "All body-part entries resolved. \u2713")

              TISSUE_DESCRIPTION                bodypar
0                     WHOLE FISH           Whole animal
4   FLESH WITHOUT BONES (FILETS)    Flesh without bones
14           STOMACH + INTESTINE  Stomach and intestine
21                 WHOLE ANIMALS           Whole animal

**Assemble the final mapping**

The steps above (unique values, fuzzy match, expert overrides, verification) told us what the correct MARIS translations are. The `make_lut_from` function packages that knowledge into a callable that the Transformer can use later.

In [ ]:
#| exports
lut_tissues = make_lut_from(provider_lut_tissues,
                             'TISSUE', 'TISSUE_DESCRIPTION', 'BODY_PART',
                             fixes=fixes_biota_tissues)

Verify body part lookup on mock data:

In [ ]:
# Verify body part lookup on mock data
dfs_mock = {'BIOTA': pd.DataFrame({'tissue': [1, 5, 12]})}
tfm = Transformer(dfs_mock, cbs=[RemapCB(lut=lut_tissues, col_remap='BODY_PART', col_src='tissue')])
tfm()
test_eq(tfm.dfs['BIOTA']['BODY_PART'].dtype, 'int64')
print("BODY_PART mapped as integer on mock data. \u2713")

BODY_PART mapped as integer on mock data. ✓

Map body part on real HELCOM Biota data:

In [ ]:
#| eval: false
tfm = Transformer({'BIOTA': dfs['BIOTA'].copy()}, cbs=[
    LowerStripNameCB(col_src='nuclide', col_dst='NUCLIDE'),
    RemapCB(lut=lut_tissues, col_remap='BODY_PART', col_src='tissue')])
dfs_out = tfm()
test_eq(dfs_out['BIOTA']['BODY_PART'].isna().sum(), 0)
test_eq(dfs_out['BIOTA']['BODY_PART'].dtype, 'int64')
print(f'BODY_PART mapped to integer MARIS IDs across {len(dfs_out['BIOTA'])} rows. \u2713')

BODY_PART mapped to integer MARIS IDs across 16124 rows. ✓

## Remap Biological Group

Unlike nuclide names, species, and body parts which required fuzzy matching against MARIS nomenclature followed by expert overrides, the biological group assignment is straightforward. The MARIS `SPECIES` lookup table already includes a `biogroup_id` column. Since each HELCOM Biota row now has `SPECIES` as an integer MARIS ID (mapped in the previous step), we just need to look up the corresponding biological group.

In [ ]:
#| exports
lut_biogroup = get_lut('SPECIES', key='species_id', value='biogroup_id')

Let's verify this works on mock data. We assign `SPECIES` IDs (as if the species-remap step already ran), then look up `BIO_GROUP`:

In [ ]:
# Verify biogroup lookup on mock species IDs
dfs_mock = {'BIOTA': pd.DataFrame({'SPECIES': [271, 274, 0]})}
tfm = Transformer(dfs_mock, cbs=[
    RemapCB(lut=lut_biogroup, col_remap='BIO_GROUP', col_src='SPECIES', grps=['BIOTA'])
])
tfm()
test_eq(tfm.dfs['BIOTA']['BIO_GROUP'].to_list(), [4, 14, 0])
print('BIO_GROUP mapped correctly on mock data. ✓')

BIO_GROUP mapped correctly on mock data. ✓

Now apply to real HELCOM Biota data, chained after the species remap:

In [ ]:
#| eval: false
tfm = Transformer({'BIOTA': dfs['BIOTA'].copy()}, cbs=[
    LowerStripNameCB(col_src='nuclide', col_dst='NUCLIDE'),
    RemapCB(lut=species_lut, col_remap='SPECIES', col_src='rubin'),
    RemapCB(lut=lut_biogroup, col_remap='BIO_GROUP', col_src='SPECIES'),
])
dfs_out = tfm()
test_eq(dfs_out['BIOTA']['BIO_GROUP'].isna().sum(), 0)
test_eq(dfs_out['BIOTA']['BIO_GROUP'].dtype, 'int64')
print(f'BIO_GROUP mapped to integer MARIS IDs across {len(dfs_out["BIOTA"])} rows. ✓')

BIO_GROUP mapped to integer MARIS IDs across 16124 rows. ✓

## Remap Sediment Types

HELCOM sediment types are recorded as integer `SEDI` codes documented in the accompanying `SEDIMENT_TYPE.csv` lookup table. We reconcile these with the MARIS sediment-type nomenclature following the same inspect-match-fix workflow used for nuclide names and species above.

In [ ]:
#| exports
provider_lut_sed = pd.read_csv(f'{src_dir}/SEDIMENT_TYPE.csv')
print(provider_lut_sed.head())

   SEDI SEDIMENT TYPE RECOMMENDED TO BE USED
0   -99       NO DATA                    NaN
1     0        GRAVEL                    YES
2     1          SAND                    YES
3     2     FINE SAND                     NO
4     3          SILT                    YES

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER

The `SEDI` values `56` and `73` are not found in the `SEDIMENT_TYPE.csv` lookup table provided. Note there are many `nan` values. We reassign them to `-99` for now but should be clarified/fixed. This is demonstrated below.

:::

In [ ]:
#| eval: false
set(dfs['SEDIMENT']['sedi'].unique()) - set(provider_lut_sed['SEDI'])

{np.float64(56.0), np.float64(73.0), np.float64(nan)}

**Try an automatic mapping**

*Derive provider sediment types from the lookup table and fuzzy-match against MARIS reference.*

In [ ]:
#| eval: false
maris_ref = get_lut('SED_TYPE', as_df=True)

print("provider_lut_sed:", provider_lut_sed.columns.tolist())
print("maris_ref:   ", maris_ref.columns.tolist())

merged = fuzzy_merge(provider_lut_sed, maris_ref, left_on='SEDIMENT TYPE', right_on='sedtype')

provider_lut_sed: ['SEDI', 'SEDIMENT TYPE', 'RECOMMENDED TO BE USED']

maris_ref:    ['sedtype_id', 'sedtype']

**Fix what it got wrong**

Apply expert overrides for cases the fuzzy match could not resolve correctly. Two are simple typos in the provider lookup table (`MUD AND GARVEL` → `Mud and gravel`, `CLACIAL CLAY` → `Glacial clay`). `NO DATA` maps to `(Not available)`.

:::{.callout-important}
## FEEDBACK TO MARIS DATA TEAM

The MARIS `SED_TYPE` lookup table uses parenthesised `(Not available)` for its sentinel entry, while every other MARIS reference table uses the bare `Not available` (e.g. `SPECIES`, `BODY_PART`, `UNIT`). This inconsistency should be aligned so that all LUTs use the same sentinel form.
:::

In [ ]:
#| exports
# Expert overrides for sediment type names
# 'NO DATA' maps to '(Not available)' rather than 'Not available' due to 
# an inconsistency in the MARIS SED_TYPE reference table — the sentinel entry 
# uses parentheses while other LUTs use the bare form. This should be aligned.
fixes_sediments = {
    'NO DATA': '(Not available)',
    'MUD AND GARVEL': 'Mud and gravel',
    'CLACIAL CLAY': 'Glacial clay',
}

In [ ]:
#| eval: false
fixed = fix_lut(merged, fixes_sediments, maris_ref,
                left_on='SEDIMENT TYPE', right_on='sedtype', id_col='sedtype_id')
unresolved = fixed[fixed['score'] > 0]
print(unresolved[['SEDIMENT TYPE', 'sedtype']] if len(unresolved) else "All sediment type entries resolved. \u2713")

All sediment type entries resolved. ✓

The steps above (unique values, fuzzy match, expert overrides, verification) told us what the correct MARIS translations are. The `make_lut_from` function packages that knowledge, the expert fixes and the MARIS reference table, into a single function that the Transformer can call later, when it is processing data through the pipeline.

A dedicated `CleanSedimentCodesCB` replaces the invalid SEDI codes (56, 73, NaN) with -99 before the nomenclature lookup, making it explicit which step handles data-cleaning vs. nomenclature mapping. When the data provider fixes these codes, simply drop this callback from the pipeline.

In [ ]:
#| exports
sed_replace_lut = {56: -99, 73: -99}

In [ ]:
#| exports
class CleanSedimentCodesCB(PerGroupCB):
    "Replace invalid HELCOM SEDI codes with -99 sentinel before nomenclature lookup."
    grps = ['SEDIMENT']
    def __init__(self, replace_lut): store_attr()
    def each_grp(self, grp, df, tfm):
        df['sedi'] = df['sedi'].replace(self.replace_lut).fillna(-99)

In [ ]:
#| exports
sediment_lut = make_lut_from(provider_lut_sed, 'SEDI', 'SEDIMENT TYPE', 'SED_TYPE', fixes=fixes_sediments)

Verify sediment type lookup on mock data:

In [ ]:
#| eval: false
dfs_mock = {'SEDIMENT': pd.DataFrame({'sedi': [0, 1, -99, 56, 73]})}
tfm = Transformer(dfs_mock, cbs=[
    CleanSedimentCodesCB(replace_lut=sed_replace_lut),
    RemapCB(lut=sediment_lut, col_remap='SED_TYPE', col_src='sedi'),
])
tfm()
test_eq(tfm.dfs['SEDIMENT']['SED_TYPE'].dtype, 'int64')
print('SED_TYPE mapped as integer on mock data.')

array([ 0,  2, 58, 30, 59, 55, 56, 36, 29, 47,  4, 54, 33,  6, 44, 42, 48,
       61, 57, 28, 49, 32, 45, 39, 46, 38, 31, 60, 62, 26, 53, 52,  1, 51,
       37, 34, 50,  7, 10, 41, 43, 35])

Apply sediment type lookup to real HELCOM SEDIMENT data:

In [ ]:
#| eval: false
tfm = Transformer(dfs, cbs=[
    CleanSedimentCodesCB(replace_lut=sed_replace_lut),
    RemapCB(lut=sediment_lut, col_remap='SED_TYPE', col_src='sedi', grps=['SEDIMENT']),
])
dfs_out = tfm()
test_eq(dfs_out['SEDIMENT']['SED_TYPE'].isna().sum(), 0)
test_eq(dfs_out['SEDIMENT']['SED_TYPE'].dtype, 'int64')
print(f'SED_TYPE mapped to integer MARIS IDs across {len(dfs_out["SEDIMENT"])} rows.')

SED_TYPE mapped to integer MARIS IDs across 40743 rows.

## Remap Filtering Status

HELCOM filtered status is encoded as follows in the `FILT` column:

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)
lut_from(dfs, 'filt').head(5)

   index value
0      0     F
1      1     N
2      2     n
3      3   NaN

MARIS uses a different encoding for filtered status:

In [ ]:
#| eval: false
pd.read_excel(filtered_lut_path())

   id            name
0  -1  Not applicable
1   0   Not available
2   1             Yes
3   2              No

For only four categories to remap, the `Remapper` is an overkill. We can use a simple dictionary to map the values:

In [ ]:
#| exports
lut_filtered = {
    'N': 2, # No
    'n': 2, # No
    'F': 1 # Yes
}

`RemapFiltCB` converts the HELCOM `filt` data to the MARIS `FILT` format.

In [ ]:
#| exports
class RemapFiltCB(PerGroupCB):
    "Lookup filt value in dataframe using the lookup table."
    def __init__(self,
                 lut_filtered: dict=lut_filtered, # Dictionary mapping filt codes to their corresponding names
                ):
        fc.store_attr()

    def each_grp(self, grp, df, tfm):
        if 'filt' in df.columns: df['FILT'] = df['filt'].map(lambda x: self.lut_filtered.get(x, 0))

For instance:

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)
tfm = Transformer(dfs, cbs=[RemapFiltCB(lut_filtered)])

print(tfm()['SEAWATER']['FILT'].unique())

[0 2 1]

## Add Sample ID

- `SMP_ID` is an internal unique identifier for each sample
- `SMP_ID_PROVIDER` is provided by the data provider

In [ ]:
# | exports
class AddSampleIDCB(PerGroupCB):
    "Generate a SMP_ID from the KEY values in the HELCOM dataset."
    def each_grp(self, grp, df, tfm):
        df['SMP_ID'] = range(1, len(df) + 1)
        df['SMP_ID_PROVIDER'] = df['key'].astype(str)

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)
tfm = Transformer(dfs, cbs=[
                        AddSampleIDCB(),
                        CompareDfsAndTfmCB(dfs)
                        ])
tfm()

print(f'Number of unique sample ids in SEAWATER: {tfm.dfs["SEAWATER"]["SMP_ID"].unique().size}')
print(f'Number of unique sample ids in BIOTA: {tfm.dfs["BIOTA"]["SMP_ID"].unique().size}')
print(f'Number of unique sample ids in SEDIMENT: {tfm.dfs["SEDIMENT"]["SMP_ID"].unique().size}')
print(pd.DataFrame.from_dict(tfm.compare_stats) , '\n')

Number of unique sample ids in SEAWATER: 21634
Number of unique sample ids in BIOTA: 16124
Number of unique sample ids in SEDIMENT: 40744
                                               BIOTA  SEAWATER  SEDIMENT
Original row count (dfs)                       16124     21634     40744
Transformed row count (tfm.dfs)                16124     21634     40744
Rows removed from original (tfm.dfs_removed)       0         0         0
Rows created in transformed (tfm.dfs_created)      0         0         0

In [ ]:
#| eval: false
with pd.option_context('display.max_columns', None):
    display(tfm.dfs['SEAWATER'].head())

,key,nuclide,method,< value_bq/m³,value_bq/m³,error%_m³,date_of_entry_x,country,laboratory,sequence,date,year,month,day,station,latitude (ddmmmm),latitude (dddddd),longitude (ddmmmm),longitude (dddddd),tdepth,sdepth,salin,ttemp,filt,mors_subbasin,helcom_subbasin,date_of_entry_y,SMP_ID,SMP_ID_PROVIDER
0,WKRIL2012003,CS137,NaN,NaN,5.3,32.0,08/20/14 00:00:00,90.0,KRIL,2012003.0,05/23/12 00:00:00,2012.0,5.0,23.0,RU10,60.05,60.0833,29.20,29.3333,NaN,0.0,NaN,NaN,NaN,11.0,11.0,08/20/14 00:00:00,1,WKRIL2012003
1,WKRIL2012004,CS137,NaN,NaN,19.9,20.0,08/20/14 00:00:00,90.0,KRIL,2012004.0,05/23/12 00:00:00,2012.0,5.0,23.0,RU10,60.05,60.0833,29.20,29.3333,NaN,29.0,NaN,NaN,NaN,11.0,11.0,08/20/14 00:00:00,2,WKRIL2012004
2,WKRIL2012005,CS137,NaN,NaN,25.5,20.0,08/20/14 00:00:00,90.0,KRIL,2012005.0,06/17/12 00:00:00,2012.0,6.0,17.0,RU11,59.26,59.4333,23.09,23.1500,NaN,0.0,NaN,NaN,NaN,11.0,3.0,08/20/14 00:00:00,3,WKRIL2012005
3,WKRIL2012006,CS137,NaN,NaN,17.0,29.0,08/20/14 00:00:00,90.0,KRIL,2012006.0,05/24/12 00:00:00,2012.0,5.0,24.0,RU19,60.15,60.2500,27.59,27.9833,NaN,0.0,NaN,NaN,NaN,11.0,11.0,08/20/14 00:00:00,4,WKRIL2012006
4,WKRIL2012007,CS137,NaN,NaN,22.2,18.0,08/20/14 00:00:00,90.0,KRIL,2012007.0,05/24/12 00:00:00,2012.0,5.0,24.0,RU19,60.15,60.2500,27.59,27.9833,NaN,39.0,NaN,NaN,NaN,11.0,11.0,08/20/14 00:00:00,5,WKRIL2012007

## Add depths

The HELCOM dataset includes a column for the sampling depth (`SDEPTH`) for the `SEAWATER` and `BIOTA` datasets. Additionally, it contains a column for the total depth (`TDEPTH`) applicable to both the `SEDIMENT` and `SEAWATER` datasets. In this section, we will create a callback to incorporate both the sampling depth (`smp_depth`) and total depth (`tot_depth`) into the MARIS dataset.

In [ ]:
#| exports
class AddDepthCB(PerGroupCB):
    "Ensure depth values are floats and add 'SMP_DEPTH' and 'TOT_DEPTH' columns."
    def each_grp(self, grp, df, tfm):
        if 'sdepth' in df.columns: df['SMP_DEPTH'] = df['sdepth'].astype(float)
        if 'tdepth' in df.columns: df['TOT_DEPTH'] = df['tdepth'].astype(float)

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)
tfm = Transformer(dfs, cbs=[AddDepthCB()])
tfm()
for grp in tfm.dfs.keys():  
    if 'SMP_DEPTH' in tfm.dfs[grp].columns and 'TOT_DEPTH' in tfm.dfs[grp].columns:
        print(f'{grp}:', tfm.dfs[grp][['SMP_DEPTH','TOT_DEPTH']].drop_duplicates())
    elif 'SMP_DEPTH' in tfm.dfs[grp].columns:
        print(f'{grp}:', tfm.dfs[grp][['SMP_DEPTH']].drop_duplicates())
    elif 'TOT_DEPTH' in tfm.dfs[grp].columns:
        print(f'{grp}:', tfm.dfs[grp][['TOT_DEPTH']].drop_duplicates())

BIOTA:        SMP_DEPTH
0            NaN
78         22.00
88         39.00
96         40.00
183        65.00
...          ...
15874      43.10
15921      30.43
15984       7.60
15985       5.50
15988      11.20

[301 rows x 1 columns]
SEAWATER:        SMP_DEPTH  TOT_DEPTH
0            0.0        NaN
1           29.0        NaN
4           39.0        NaN
6           62.0        NaN
10          71.0        NaN
...          ...        ...
21059       15.0       15.0
21217        7.0       16.0
21235       19.2       21.0
21312        1.0        5.5
21521        0.5        NaN

[1686 rows x 2 columns]
SEDIMENT:        TOT_DEPTH
0           25.0
6           61.0
19          31.0
33          39.0
42          36.0
...          ...
35882        3.9
36086      103.0
36449      108.9
36498        4.5
36899      125.0

[195 rows x 1 columns]

## Add Salinity

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER

The HELCOM dataset includes a column for the salinity of the water (`salin`). According to the HELCOM documentation, the `salin` column represents "Salinity of water in PSU units".

In the SEAWATER dataset, three entries have salinity values greater than 50 PSU. While salinity values greater than 50 PSU are possible, these entries may require further verification. Notably, these three entries have a salinity value of 99.99 PSU, which suggests potential data entry errors.
:::

In [ ]:
#| eval: false
tfm.dfs['SEAWATER'][tfm.dfs['SEAWATER']['salin'] > 50]

,key,nuclide,method,< value_bq/m³,value_bq/m³,error%_m³,date_of_entry_x,country,laboratory,sequence,...,tdepth,sdepth,salin,ttemp,filt,mors_subbasin,helcom_subbasin,date_of_entry_y,SMP_DEPTH,TOT_DEPTH
12288,WDHIG1998072,CS137,3,NaN,40.1,1.6,NaN,6.0,DHIG,1998072.0,...,25.0,0.0,99.99,5.0,F,5.0,15.0,NaN,0.0,25.0
12289,WDHIG1998072,CS134,3,NaN,1.1,23.6,NaN,6.0,DHIG,1998072.0,...,25.0,0.0,99.99,5.0,F,5.0,15.0,NaN,0.0,25.0
12290,WDHIG1998072,SR90,2,NaN,8.5,1.9,NaN,6.0,DHIG,1998072.0,...,25.0,0.0,99.99,5.0,F,5.0,15.0,NaN,0.0,25.0

Lets add the salinity values to the SEAWATER DataFrame.

In [ ]:
#| exports
class AddSalinityCB(PerGroupCB):
    "Add salinity to all DataFrames."
    def __init__(self, salinity_col: str = 'salin'): fc.store_attr()

    def each_grp(self, grp, df, tfm):
        if self.salinity_col in df.columns: df['SAL'] = df[self.salinity_col].astype(float)

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)
tfm = Transformer(dfs, cbs=[AddSalinityCB()])
tfm()
for grp in tfm.dfs.keys():  
    if 'SAL' in tfm.dfs[grp].columns:
        print(f'{grp}:', tfm.dfs[grp][['SAL']].drop_duplicates())

SEAWATER:           SAL
0         NaN
97      7.570
98      7.210
101     7.280
104     7.470
...       ...
21449  11.244
21450   7.426
21451   9.895
21452   2.805
21453   7.341

[2766 rows x 1 columns]

## Add Station

In [ ]:
#| exports
class AddStationCB(PerGroupCB):
    "Add station to all DataFrames."
    def each_grp(self, grp, df, tfm): df['STATION'] = df['station'].fillna('').astype(str)

In [ ]:
#| eval: false  
dfs = load_data(src_dir, use_cache=True)
tfm = Transformer(dfs, cbs=[AddStationCB()])
tfm()['BIOTA'].head()

,key,nuclide,method,< value_bq/kg,value_bq/kg,basis,error%,number,date_of_entry_x,country,...,tissue,no,length,weight,dw%,loi%,mors_subbasin,helcom_subbasin,date_of_entry_y,STATION
0,BVTIG2012041,CS134,VTIG01,<,0.010140,W,NaN,NaN,02/27/14 00:00:00,6.0,...,5,16.0,45.7,948.0,18.453,92.9,2.0,16,02/27/14 00:00:00,SD24
1,BVTIG2012041,K40,VTIG01,,135.300000,W,3.57,NaN,02/27/14 00:00:00,6.0,...,5,16.0,45.7,948.0,18.453,92.9,2.0,16,02/27/14 00:00:00,SD24
2,BVTIG2012041,CO60,VTIG01,<,0.013980,W,NaN,NaN,02/27/14 00:00:00,6.0,...,5,16.0,45.7,948.0,18.453,92.9,2.0,16,02/27/14 00:00:00,SD24
3,BVTIG2012041,CS137,VTIG01,,4.338000,W,3.48,NaN,02/27/14 00:00:00,6.0,...,5,16.0,45.7,948.0,18.453,92.9,2.0,16,02/27/14 00:00:00,SD24
4,BVTIG2012040,CS134,VTIG01,<,0.009614,W,NaN,NaN,02/27/14 00:00:00,6.0,...,5,17.0,45.9,964.0,18.458,92.9,2.0,16,02/27/14 00:00:00,SD24

## Add Temperature

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER

The HELCOM dataset includes a column for the temperature of the water (`ttemp`). According to the HELCOM documentation, the `ttemp` column represents:
> 'Water temperature in Celsius (ºC) degrees of sampled water'

In the SEAWATER dataset, several entries have temperature values greater than 50ºC. These entries may require further verification. Notably, these entries have a temperature value of 99.99ºC, which suggests potential data entry errors, see below.
:::

In [ ]:
#| eval: false
t_df= tfm.dfs['SEAWATER'][tfm.dfs['SEAWATER']['ttemp'] > 50]
print('Number of entries with temperature greater than 50ºC: ', t_df.shape[0])
t_df.head()

Number of entries with temperature greater than 50ºC:  92

,key,nuclide,method,< value_bq/m³,value_bq/m³,error%_m³,date_of_entry_x,country,laboratory,sequence,...,longitude (dddddd),tdepth,sdepth,salin,ttemp,filt,mors_subbasin,helcom_subbasin,date_of_entry_y,STATION
5954,WDHIG1995559,CS134,4,NaN,1.7,15.0,NaN,6.0,DHIG,1995559.0,...,10.2033,13.0,11.0,14.81,99.9,N,5.0,15.0,NaN,KFOTN6
5955,WDHIG1995559,CS137,4,NaN,58.7,2.0,NaN,6.0,DHIG,1995559.0,...,10.2033,13.0,11.0,14.81,99.9,N,5.0,15.0,NaN,KFOTN6
5960,WDHIG1995569,CS134,4,NaN,1.4,12.0,NaN,6.0,DHIG,1995569.0,...,10.2777,14.0,12.0,14.80,99.9,N,5.0,15.0,NaN,LTKIEL
5961,WDHIG1995569,CS137,4,NaN,62.8,1.0,NaN,6.0,DHIG,1995569.0,...,10.2777,14.0,12.0,14.80,99.9,N,5.0,15.0,NaN,LTKIEL
5964,WDHIG1995571,CS134,4,NaN,1.5,17.0,NaN,6.0,DHIG,1995571.0,...,10.2000,19.0,17.0,14.59,99.9,N,5.0,15.0,NaN,STOLGR

Lets add the temperature values to the SEAWATER DataFrame.

In [ ]:
#| exports
class AddTemperatureCB(PerGroupCB):
    "Add temperature to all DataFrames."
    def __init__(self, temperature_col: str = 'ttemp'): fc.store_attr()

    def each_grp(self, grp, df, tfm):
        if self.temperature_col in df.columns: df['TEMP'] = df[self.temperature_col].astype(float)

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)
tfm = Transformer(dfs, cbs=[AddTemperatureCB()])
tfm()
for grp in tfm.dfs.keys():  
    if 'TEMP' in tfm.dfs[grp].columns:
        print(f'{grp}:', tfm.dfs[grp][['TEMP']].drop_duplicates())

SEAWATER:         TEMP
0        NaN
987     7.80
990     6.50
993     4.10
996     4.80
...      ...
21521   0.57
21523  18.27
21525  21.54
21529   4.94
21537   2.35

[1086 rows x 1 columns]

## Add slice position (TOP and BOTTOM)

In [ ]:
#| exports
class RemapSedSliceTopBottomCB(PerGroupCB):
    "Remap Sediment slice top and bottom to MARIS format."
    grps = ['SEDIMENT']
    def each_grp(self, grp, df, tfm):
        df['TOP'] = df['uppsli']
        df['BOTTOM'] = df['lowsli']

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)
tfm = Transformer(dfs, cbs=[RemapSedSliceTopBottomCB()])
tfm()
print(tfm.dfs['SEDIMENT'][['TOP','BOTTOM']].head())

    TOP  BOTTOM
0  15.0    20.0
1  20.0    25.0
2  25.0    30.0
3  30.0    35.0
4  35.0    40.0

## Add dry weight, wet weight and percentage weight

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER

Entries for the ``BASIS`` value of the ``BIOTA`` dataset report a value of `F` which is not consistent with the HELCOM description provided in the metadata. The `GUIDELINES FOR MONITORING OF RADIOACTIVE SUBSTANCES` was obtained from [here](https://metadata.helcom.fi/geonetwork/srv/fin/catalog.search#/metadata/2fdd2d46-0329-40e3-bf96-cb08c7206a24).

:::

Lets take a look at the BIOTA BASIS values:

In [ ]:
#| eval: false
dfs['BIOTA']['basis'].unique()

<ArrowStringArray>
['W', nan, 'D', 'F']
Length: 4, dtype: str

Number of entries for each ``BASIS`` value:

In [ ]:
#| eval: false
dfs['BIOTA']['basis'].value_counts()

basis
W    12164
D     3868
F       25
Name: count, dtype: int64

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER

Some entries for ``DW%`` (Dry weight as percentage (%) of fresh weight) are much higher than 100%. Additionally, ``DW%`` is repoted as 0% in some cases.

:::

For BIOTA, the number of entries for ``DW%`` higher than 100%:

In [ ]:
#| eval: false
dfs['BIOTA']['dw%'][dfs['BIOTA']['dw%'] > 100].count()

np.int64(20)

For BIOTA, the number of entries for ``DW%`` equal to 0%:

In [ ]:
#| eval: false
dfs['BIOTA']['dw%'][dfs['BIOTA']['dw%'] == 0].count()

np.int64(6)

For SEDIMENT, the number of entries for ``DW%`` higher than 100%:

In [ ]:
#| eval: false
dfs['SEDIMENT']['dw%'][dfs['SEDIMENT']['dw%'] > 100].count()

np.int64(625)

For SEDIMENT, the number of entries for ``DW%`` equal to 0%:

In [ ]:
#| eval: false
dfs['SEDIMENT']['dw%'][dfs['SEDIMENT']['dw%'] == 0].count()

np.int64(302)

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER

Several SEDIMENT entries have `DW%` (Dry weight as percentage of fresh weight) values less than 1%. While technically possible, this would indicate samples contained more than 99% water content.

:::

For SEDIMENT, the number of entries for ``DW%`` less than 1% but greater than 0.001%:

In [ ]:
#| eval: false
percent=1
dfs['SEDIMENT']['dw%'][(dfs['SEDIMENT']['dw%'] < percent) & (dfs['SEDIMENT']['dw%'] > 0.001)].count()

np.int64(24)

Lets take a look at the MARIS description of the `percentwt`, `drywt` and `wetwt` variables:

- `percentwt`: Dry weight as ratio of fresh weight, expressed as a decimal .
- `drywt`: Dry weight in grams.
- `wetwt`: Fresh weight in grams.

Lets take a look at the HELCOM dataset, the weight of the sample is not reported for ``SEDIMENT``. However, the percentage dry weight is reported as `DW%`.

In [ ]:
#| eval: false
dfs['SEDIMENT'].columns

Index(['key', 'nuclide', 'method', '< value_bq/kg', 'value_bq/kg', 'error%_kg',
       '< value_bq/m²', 'value_bq/m²', 'error%_m²', 'date_of_entry_x',
       'country', 'laboratory', 'sequence', 'date', 'year', 'month', 'day',
       'station', 'latitude (ddmmmm)', 'latitude (dddddd)',
       'longitude (ddmmmm)', 'longitude (dddddd)', 'device', 'tdepth',
       'uppsli', 'lowsli', 'area', 'sedi', 'oxic', 'dw%', 'loi%',
       'mors_subbasin', 'helcom_subbasin', 'sum_link', 'date_of_entry_y'],
      dtype='str')

The BIOTA dataset reports the weight of the sample as `WEIGHT` and the percentage dry weight as `DW%`. The `BASIS` column describes the basis of the value reported. Lets create a callback to include the `PERCENTWT`, `DRYWT` and `WETWT` columns in the MARIS dataset.

In [ ]:
#| exports
class LookupDryWetPercentWeightCB(PerGroupCB):
    "Lookup dry-wet ratio and format for MARIS."
    def each_grp(self, grp, df, tfm):
        if 'dw%' in df.columns: self._apply_dry_wet_ratio(df)
        if 'weight' in df.columns and 'basis' in df.columns:
            self._correct_basis(df)
            self._apply_weight(df)

    def _apply_dry_wet_ratio(self, df: pd.DataFrame) -> None:
        df['PERCENTWT'] = df['dw%'] / 100
        df.loc[df['PERCENTWT'] == 0, 'PERCENTWT'] = np.nan

    def _correct_basis(self, df: pd.DataFrame) -> None:
        df.loc[df['basis'] == 'F', 'basis'] = 'W'

    def _apply_weight(self, df: pd.DataFrame) -> None:
        dry_condition = df['basis'] == 'D'
        wet_condition = df['basis'] == 'W'
        df.loc[dry_condition, 'DRYWT'] = df['weight']
        df.loc[dry_condition & df['PERCENTWT'].notna(), 'WETWT'] = df['weight'] / df['PERCENTWT']
        df.loc[wet_condition, 'WETWT'] = df['weight']
        df.loc[wet_condition & df['PERCENTWT'].notna(), 'DRYWT'] = df['weight'] * df['PERCENTWT']

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)
tfm = Transformer(dfs, cbs=[
                            LookupDryWetPercentWeightCB(),
                            CompareDfsAndTfmCB(dfs)
                            ])

tfm()
print(pd.DataFrame.from_dict(tfm.compare_stats) , '\n')
print('BIOTA:', tfm.dfs['BIOTA'][['PERCENTWT','DRYWT','WETWT']].head(), '\n')
print('SEDIMENT:', tfm.dfs['SEDIMENT']['PERCENTWT'].unique())

                                               BIOTA  SEAWATER  SEDIMENT
Original row count (dfs)                       16124     21634     40744
Transformed row count (tfm.dfs)                16124     21634     40744
Rows removed from original (tfm.dfs_removed)       0         0         0
Rows created in transformed (tfm.dfs_created)      0         0         0

BIOTA:    PERCENTWT      DRYWT  WETWT
0    0.18453  174.93444  948.0
1    0.18453  174.93444  948.0
2    0.18453  174.93444  948.0
3    0.18453  174.93444  948.0
4    0.18458  177.93512  964.0

SEDIMENT: [       nan 0.1        0.13       ... 0.24418605 0.25764192 0.26396495]

Note that the dry weight is greater than the wet weight for some entries in the BIOTA dataset due to the DW% being greater than 100%, see above. Lets take a look at the number of entries where this is the case:

In [ ]:
#|eval: false
tfm.dfs['BIOTA'][['DRYWT','WETWT']][tfm.dfs['BIOTA']['DRYWT'] > tfm.dfs['BIOTA']['WETWT']].count()

DRYWT    20
WETWT    20
dtype: int64

## Standardize Coordinates

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER

Column names for geographical coordinates are inconsistent across sample types (biota, sediment, seawater). Sometimes using parentheses, sometimes not.

:::

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)
for grp in dfs.keys():
    print(f'{grp}: {[col for col in dfs[grp].columns if "lon" in col or "lat" in col]}')

BIOTA: ['latitude ddmmmm', 'latitude dddddd', 'longitude ddmmmm', 'longitude dddddd']
SEAWATER: ['latitude (ddmmmm)', 'latitude (dddddd)', 'longitude (ddmmmm)', 'longitude (dddddd)']
SEDIMENT: ['latitude (ddmmmm)', 'latitude (dddddd)', 'longitude (ddmmmm)', 'longitude (dddddd)']

:::{.callout-important}
## FEEDBACK TO DATA PROVIDER

HELCOM SEAWATER data includes values of 0 or nan for both latitude and longitude. 

:::

Lets create a callback to parse the coordinates of the HELCOM dataset.

In [ ]:
#| exports
class ParseCoordinatesCB(PerGroupCB):
    "Get geographical coordinates from columns expressed in degrees decimal format or from columns in degrees/minutes decimal format where degrees decimal format is missing or zero."
    def __init__(self, 
                 fn_convert_cor: Callable # Function that converts coordinates from degree-minute to decimal degree format
                 ):
        fc.store_attr()

    def each_grp(self, grp, df, tfm): self._format_coordinates(df)

    def _format_coordinates(self, df:pd.DataFrame) -> None:
        coord_cols = self._get_coord_columns(df.columns)
        for coord in ['lat', 'lon']:
            decimal_col, minute_col = coord_cols[f'{coord}_d'], coord_cols[f'{coord}_m']
            df[decimal_col] = pd.to_numeric(df[decimal_col], errors='coerce')
            df[minute_col] = pd.to_numeric(df[minute_col], errors='coerce')
            condition = df[decimal_col].isna() | (df[decimal_col] == 0)
            df[coord.upper()] = np.where(condition,
                                 df[minute_col].apply(self._safe_convert),
                                 df[decimal_col])
        df.dropna(subset=['LAT', 'LON'], inplace=True)

    def _get_coord_columns(self, columns) -> dict:
        return {
            'lon_d': self._find_coord_column(columns, 'lon', 'dddddd'),
            'lat_d': self._find_coord_column(columns, 'lat', 'dddddd'),
            'lon_m': self._find_coord_column(columns, 'lon', 'ddmmmm'),
            'lat_m': self._find_coord_column(columns, 'lat', 'ddmmmm')
        }

    def _find_coord_column(self, columns, coord_type, coord_format) -> str:
        pattern = re.compile(f'{coord_type}.*{coord_format}', re.IGNORECASE)
        matching_columns = [col for col in columns if pattern.search(col)]
        return matching_columns[0] if matching_columns else None

    def _safe_convert(self, value) -> str:
        if pd.isna(value): return value
        try:
            return self.fn_convert_cor(value)
        except Exception as e:
            print(f"Error converting value {value}: {e}")
            return value

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)
tfm = Transformer(dfs, cbs=[                    
                            ParseCoordinatesCB(ddmm_to_dd),
                            CompareDfsAndTfmCB(dfs)
                            ])
tfm()
print(pd.DataFrame.from_dict(tfm.compare_stats) , '\n')
print(tfm.dfs['BIOTA'][['LAT','LON']])

                                               BIOTA  SEAWATER  SEDIMENT
Original row count (dfs)                       16124     21634     40744
Transformed row count (tfm.dfs)                16124     21626     40743
Rows removed from original (tfm.dfs_removed)       0         8         1
Rows created in transformed (tfm.dfs_created)      0         0         0

             LAT        LON
0      54.283333  12.316667
1      54.283333  12.316667
2      54.283333  12.316667
3      54.283333  12.316667
4      54.283333  12.316667
...          ...        ...
16119  61.241500  21.395000
16120  61.241500  21.395000
16121  61.343333  21.385000
16122  61.343333  21.385000
16123  61.343333  21.385000

[16124 rows x 2 columns]

Lets review the rows removed from SEAWATER dataset during the parsing of coordinates:

In [ ]:
#|eval: false
with pd.option_context('display.max_columns', None, 'display.max_colwidth', None):
    display(tfm.dfs_removed['SEAWATER'])

,key,nuclide,method,< value_bq/m³,value_bq/m³,error%_m³,date_of_entry_x,country,laboratory,sequence,date,year,month,day,station,latitude (ddmmmm),latitude (dddddd),longitude (ddmmmm),longitude (dddddd),tdepth,sdepth,salin,ttemp,filt,mors_subbasin,helcom_subbasin,date_of_entry_y
20556,WSSSM2015009,H3,STYR201,<,2450.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20557,WSSSM2015010,H3,STYR201,NaN,2510.0,29.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20558,WSSSM2015011,H3,STYR201,<,2450.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20559,WSSSM2015012,H3,STYR201,NaN,1740.0,41.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20560,WSSSM2015013,H3,STYR201,NaN,1650.0,43.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20561,WSSSM2015014,H3,STYR201,<,2277.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20562,WSSSM2015015,H3,STYR201,<,2277.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20563,WSSSM2015016,H3,STYR201,<,2277.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Sanitize coordinates by dropping rows where both longitude and latitude are zero or contain unrealistic values. Convert the , separator in longitude and latitude to a . separator

In [ ]:
#| eval: false
dfs = load_data(src_dir,  use_cache=True)
tfm = Transformer(dfs, cbs=[
                            ParseCoordinatesCB(ddmm_to_dd),
                            SanitizeLonLatCB(),
                            CompareDfsAndTfmCB(dfs)
                            ])

tfm()
print(pd.DataFrame.from_dict(tfm.compare_stats) , '\n')
print(tfm.dfs['BIOTA'][['LAT','LON']])

                                               BIOTA  SEAWATER  SEDIMENT
Original row count (dfs)                       16124     21634     40744
Transformed row count (tfm.dfs)                16124     21626     40743
Rows removed from original (tfm.dfs_removed)       0         8         1
Rows created in transformed (tfm.dfs_created)      0         0         0

             LAT        LON
0      54.283333  12.316667
1      54.283333  12.316667
2      54.283333  12.316667
3      54.283333  12.316667
4      54.283333  12.316667
...          ...        ...
16119  61.241500  21.395000
16120  61.241500  21.395000
16121  61.343333  21.385000
16122  61.343333  21.385000
16123  61.343333  21.385000

[16124 rows x 2 columns]

## Review all callbacks

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)
tfm = Transformer(dfs, cbs=[
                            LowerStripNameCB(col_src='nuclide', col_dst='NUCLIDE'),
                            RemapCB(lut=lut_nuclides, col_remap='NUCLIDE', col_src='NUCLIDE'),
                            ParseTimeCB(),
                            EncodeTimeCB(),
                            SplitSedimentValuesCB(coi_sediment),
                            SanitizeValueCB(coi_val),       
                            NormalizeUncCB(),
                            RemapUnitCB(),
                            RemapDetectionLimitCB(coi_dl),                           
                            RemapCB(fn_lut=lut_biota, col_remap='SPECIES', col_src='rubin', dest_grps='BIOTA'),
                            RemapCB(fn_lut=lut_tissues, col_remap='BODY_PART', col_src='tissue', dest_grps='BIOTA'),
                            RemapCB(fn_lut=lut_biogroup_from_biota, col_remap='BIO_GROUP', col_src='SPECIES', dest_grps='BIOTA'),
                            RemapSedimentCB(fn_lut=lut_sediments, replace_lut=sed_replace_lut),
                            RemapFiltCB(lut_filtered),
                            AddSampleIDCB(),
                            AddDepthCB(),
                            AddSalinityCB(),
                            AddTemperatureCB(),
                            RemapSedSliceTopBottomCB(),
                            LookupDryWetPercentWeightCB(),
                            ParseCoordinatesCB(ddmm_to_dd),
                            SanitizeLonLatCB(),
                            AddStationCB(),
                            CompareDfsAndTfmCB(dfs)
                            ])

tfm()
print(pd.DataFrame.from_dict(tfm.compare_stats) , '\n')

Warning: 8 missing time value(s) in SEAWATER
Warning: 1 missing time value(s) in SEDIMENT
                                               BIOTA  SEAWATER  SEDIMENT
Original row count (dfs)                       16124     21634     40744
Transformed row count (tfm.dfs)                16094     21473     70449
Rows removed from original (tfm.dfs_removed)      30       161       144
Rows created in transformed (tfm.dfs_created)      0         0     29849

In [ ]:
#| eval: false
tfm.dfs['SEAWATER'].head()

,key,nuclide,method,< value_bq/m³,value_bq/m³,error%_m³,date_of_entry_x,country,laboratory,sequence,...,FILT,SMP_ID,SMP_ID_PROVIDER,SMP_DEPTH,TOT_DEPTH,SAL,TEMP,LAT,LON,STATION
0,WKRIL2012003,CS137,NaN,NaN,5.3,32.0,08/20/14 00:00:00,90.0,KRIL,2012003.0,...,0,1,WKRIL2012003,0.0,NaN,NaN,NaN,60.0833,29.3333,RU10
1,WKRIL2012004,CS137,NaN,NaN,19.9,20.0,08/20/14 00:00:00,90.0,KRIL,2012004.0,...,0,2,WKRIL2012004,29.0,NaN,NaN,NaN,60.0833,29.3333,RU10
2,WKRIL2012005,CS137,NaN,NaN,25.5,20.0,08/20/14 00:00:00,90.0,KRIL,2012005.0,...,0,3,WKRIL2012005,0.0,NaN,NaN,NaN,59.4333,23.1500,RU11
3,WKRIL2012006,CS137,NaN,NaN,17.0,29.0,08/20/14 00:00:00,90.0,KRIL,2012006.0,...,0,4,WKRIL2012006,0.0,NaN,NaN,NaN,60.2500,27.9833,RU19
4,WKRIL2012007,CS137,NaN,NaN,22.2,18.0,08/20/14 00:00:00,90.0,KRIL,2012007.0,...,0,5,WKRIL2012007,39.0,NaN,NaN,NaN,60.2500,27.9833,RU19

In [ ]:
tfm.dfs['SEAWATER'].NUCLIDE.unique()

array([np.int64(33), np.int64(12), np.int64(1), np.int64(31),
       np.int64(67), np.int64(77), np.int64(72), np.int64(73),
       np.int64(75), np.int64(15), np.int64(4), np.int64(16),
       np.int64(11), np.int64(24), np.int64(14), np.int64(17),
       np.int64(13), np.int64(22), np.int64(80), np.int64(34),
       np.int64(37), np.int64(62), np.int64(64), np.int64(9),
       np.int64(68), np.int64(41), np.int64(47), np.int64(65),
       np.int64(69), np.int64(6)], dtype=object)

Lets inspect the rows that are removed for the SEAWATER data:

In [ ]:
#| eval: false
grp='SEAWATER' # 'SEAWATER', 'BIOTA' or 'SEDIMENT'
print(f'{grp}, number of dropped rows: {tfm.dfs_removed[grp].shape[0]}.')
print(f'Viewing dropped rows for {grp}:')
tfm.dfs_removed[grp]

SEAWATER, number of dropped rows: 161.
Viewing dropped rows for SEAWATER:

,key,nuclide,method,< value_bq/m³,value_bq/m³,error%_m³,date_of_entry_x,country,laboratory,sequence,...,longitude (ddmmmm),longitude (dddddd),tdepth,sdepth,salin,ttemp,filt,mors_subbasin,helcom_subbasin,date_of_entry_y
13439,WRISO2001025,CS137,RISO02,NaN,NaN,10.0,NaN,26.0,RISO,2001025.0,...,10.500,10.833333,22.0,20.0,0.00,NaN,N,5.0,5.0,NaN
14017,WLEPA2002001,CS134,LEPA02,<,NaN,NaN,NaN,93.0,LEPA,2002001.0,...,21.030,21.050000,16.0,0.0,3.77,14.40,N,4.0,9.0,NaN
14020,WLEPA2002002,CS134,LEPA02,<,NaN,NaN,NaN,93.0,LEPA,2002004.0,...,20.574,20.956667,14.0,0.0,6.57,11.95,N,4.0,9.0,NaN
14023,WLEPA2002003,CS134,LEPA02,<,NaN,NaN,NaN,93.0,LEPA,2002007.0,...,19.236,19.393333,73.0,0.0,7.00,9.19,N,4.0,9.0,NaN
14026,WLEPA2002004,CS134,LEPA02,<,NaN,NaN,NaN,93.0,LEPA,2002010.0,...,20.205,20.341700,47.0,0.0,7.06,8.65,N,4.0,9.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21542,WLRPC2023011,SR90,LRPC02,NaN,NaN,NaN,05/03/24 00:00:00,93.0,LRPC,2023011.0,...,20.480,20.800000,45.0,1.0,7.22,19.80,N,4.0,9.0,05/03/24 00:00:00
21543,WLRPC2023012,CS137,LRPC01,NaN,NaN,NaN,05/03/24 00:00:00,93.0,LRPC,2023012.0,...,20.480,20.800000,45.0,1.0,7.23,8.80,N,4.0,9.0,05/03/24 00:00:00
21544,WLRPC2023012,SR90,LRPC02,NaN,NaN,NaN,05/03/24 00:00:00,93.0,LRPC,2023012.0,...,20.480,20.800000,45.0,1.0,7.23,8.80,N,4.0,9.0,05/03/24 00:00:00
21545,WLRPC2023013,CS137,LRPC01,NaN,NaN,NaN,05/03/24 00:00:00,93.0,LRPC,2023013.0,...,20.427,20.711700,41.0,1.0,7.23,19.30,N,4.0,9.0,05/03/24 00:00:00
21546,WLRPC2023013,SR90,LRPC02,NaN,NaN,NaN,05/03/24 00:00:00,93.0,LRPC,2023013.0,...,20.427,20.711700,41.0,1.0,7.23,19.30,N,4.0,9.0,05/03/24 00:00:00

### Example change logs

In [ ]:
#| eval: false
dfs = load_data(src_dir, use_cache=True)

tfm = Transformer(dfs, cbs=[
                            LowerStripNameCB(col_src='nuclide', col_dst='NUCLIDE'),
                            RemapCB(lut=lut_nuclides, col_remap='NUCLIDE', col_src='NUCLIDE'),
                            ParseTimeCB(),
                            EncodeTimeCB(),
                            SplitSedimentValuesCB(coi_sediment),
                            SanitizeValueCB(coi_val),       
                            NormalizeUncCB(),
                            RemapUnitCB(),
                            RemapDetectionLimitCB(coi_dl),                           
                            RemapCB(fn_lut=lut_biota, col_remap='SPECIES', col_src='rubin', dest_grps='BIOTA'),
                            RemapCB(fn_lut=lut_tissues, col_remap='BODY_PART', col_src='tissue', dest_grps='BIOTA'),
                            RemapCB(fn_lut=lut_biogroup_from_biota, col_remap='BIO_GROUP', col_src='SPECIES', dest_grps='BIOTA'),
                            RemapSedimentCB(fn_lut=lut_sediments, replace_lut=sed_replace_lut),
                            RemapFiltCB(lut_filtered),
                            AddSampleIDCB(),
                            AddDepthCB(),
                            AddSalinityCB(),
                            AddTemperatureCB(),
                            RemapSedSliceTopBottomCB(),
                            LookupDryWetPercentWeightCB(),
                            ParseCoordinatesCB(ddmm_to_dd),
                            SanitizeLonLatCB(),
                            ])

tfm()
tfm.logs

Warning: 8 missing time value(s) in SEAWATER
Warning: 1 missing time value(s) in SEDIMENT

["Convert 'nuclide' column values to lowercase, strip spaces, and store in 'NUCLIDE' column.",
 'Remap data provider nuclide names to standardized MARIS nuclide names.',
 'Standardize time format across all dataframes.',
 'Encode time as seconds since epoch.',
 'Separate sediment entries into distinct rows for Bq/kg and Bq/m² measurements.',
 'Sanitize measurement values by removing blanks and standardizing to use the `VALUE` column.',
 'Convert from relative error to standard uncertainty.',
 'Set the `unit` id column in the DataFrames based on a lookup table.',
 "Remap values from 'rubin' to 'SPECIES' for groups: BIOTA.",
 "Remap values from 'tissue' to 'BODY_PART' for groups: BIOTA.",
 "Remap values from 'SPECIES' to 'BIO_GROUP' for groups: BIOTA.",
 'Lookup sediment id using lookup table.',
 'Lookup filt value in dataframe using the lookup table.',
 'Generate a SMP_ID from the KEY values in the HELCOM dataset.',
 "Ensure depth values are floats and add 'SMP_DEPTH' and 'TOT_DEPTH' columns.",
 'Remap Sediment slice top and bottom to MARIS format.',
 'Lookup dry-wet ratio and format for MARIS.',
 'Get geographical coordinates from columns expressed in degrees decimal format or from columns in degrees/minutes decimal format where degrees decimal format is missing or zero.',
 'Drop rows with invalid longitude & latitude values. Convert `,` separator to `.` separator.']

## Feed global attributes

In [ ]:
#| export
kw = ['oceanography', 'Earth Science > Oceans > Ocean Chemistry> Radionuclides',
      'Earth Science > Human Dimensions > Environmental Impacts > Nuclear Radiation Exposure',
      'Earth Science > Oceans > Ocean Chemistry > Ocean Tracers, Earth Science > Oceans > Marine Sediments',
      'Earth Science > Oceans > Ocean Chemistry, Earth Science > Oceans > Sea Ice > Isotopes',
      'Earth Science > Oceans > Water Quality > Ocean Contaminants',
      'Earth Science > Biological Classification > Animals/Vertebrates > Fish',
      'Earth Science > Biosphere > Ecosystems > Marine Ecosystems',
      'Earth Science > Biological Classification > Animals/Invertebrates > Mollusks',
      'Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans',
      'Earth Science > Biological Classification > Plants > Macroalgae (Seaweeds)']

In [ ]:
#| exports
def get_attrs(
    tfm: Transformer, # Transformer object
    zotero_key: str, # Zotero dataset record key
    kw: list = kw # List of keywords
    ) -> dict: # Global attributes
    "Retrieve all global attributes."
    return GlobAttrsFeeder(tfm.dfs, cbs=[
        BboxCB(),
        DepthRangeCB(),
        TimeRangeCB(),
        ZoteroCB(zotero_key),
        KeyValuePairCB('keywords', ', '.join(kw)),
        KeyValuePairCB('publisher_postprocess_logs', ', '.join(tfm.logs))
        ])()

In [ ]:
#| eval: false
get_attrs(tfm, zotero_key=zotero_key, kw=kw)

{'geospatial_lat_min': '31.17',
 'geospatial_lat_max': '65.75',
 'geospatial_lon_min': '9.6333',
 'geospatial_lon_max': '53.5',
 'geospatial_bounds': 'POLYGON ((9.6333 53.5, 31.17 53.5, 31.17 65.75, 9.6333 65.75, 9.6333 53.5))',
 'geospatial_vertical_max': '437.0',
 'geospatial_vertical_min': '0.0',
 'time_coverage_start': '1984-01-10T00:00:00',
 'time_coverage_end': '2023-11-30T00:00:00',
 'id': '26VMZZ2Q',
 'title': 'Environmental database - Helsinki Commission Monitoring of Radioactive Substances',
 'summary': 'MORS Environment database has been used to collate data resulting from monitoring of environmental radioactivity in the Baltic Sea based on HELCOM Recommendation 26/3.\n\nThe database is structured according to HELCOM Guidelines on Monitoring of Radioactive Substances (https://www.helcom.fi/wp-content/uploads/2019/08/Guidelines-for-Monitoring-of-Radioactive-Substances.pdf), which specifies reporting format, database structure, data types and obligatory parameters used for reporting data under Recommendation 26/3.\n\nThe database is updated and quality assured annually by HELCOM MORS EG.',
 'creator_name': '[{"creatorType": "author", "name": "HELCOM MORS"}]',
 'keywords': 'oceanography, Earth Science > Oceans > Ocean Chemistry> Radionuclides, Earth Science > Human Dimensions > Environmental Impacts > Nuclear Radiation Exposure, Earth Science > Oceans > Ocean Chemistry > Ocean Tracers, Earth Science > Oceans > Marine Sediments, Earth Science > Oceans > Ocean Chemistry, Earth Science > Oceans > Sea Ice > Isotopes, Earth Science > Oceans > Water Quality > Ocean Contaminants, Earth Science > Biological Classification > Animals/Vertebrates > Fish, Earth Science > Biosphere > Ecosystems > Marine Ecosystems, Earth Science > Biological Classification > Animals/Invertebrates > Mollusks, Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans, Earth Science > Biological Classification > Plants > Macroalgae (Seaweeds)',
 'publisher_postprocess_logs': "Convert 'nuclide' column values to lowercase, strip spaces, and store in 'NUCLIDE' column., Remap data provider nuclide names to standardized MARIS nuclide names., Standardize time format across all dataframes., Encode time as seconds since epoch., Separate sediment entries into distinct rows for Bq/kg and Bq/m² measurements., Sanitize measurement values by removing blanks and standardizing to use the `VALUE` column., Convert from relative error to standard uncertainty., Set the `unit` id column in the DataFrames based on a lookup table., Remap values from 'rubin' to 'SPECIES' for groups: BIOTA., Remap values from 'tissue' to 'BODY_PART' for groups: BIOTA., Remap values from 'SPECIES' to 'BIO_GROUP' for groups: BIOTA., Lookup sediment id using lookup table., Lookup filt value in dataframe using the lookup table., Generate a SMP_ID from the KEY values in the HELCOM dataset., Ensure depth values are floats and add 'SMP_DEPTH' and 'TOT_DEPTH' columns., Remap Sediment slice top and bottom to MARIS format., Lookup dry-wet ratio and format for MARIS., Get geographical coordinates from columns expressed in degrees decimal format or from columns in degrees/minutes decimal format where degrees decimal format is missing or zero., Drop rows with invalid longitude & latitude values. Convert `,` separator to `.` separator."}

## <a name="encoding-netcdf"></a>Encoding NetCDF

In [ ]:
#| exports
def encode(
    fname_out: str, # Output file name
    **kwargs # Additional arguments
    ) -> None:
    "Encode data to NetCDF."
    dfs = load_data(src_dir)
    tfm = Transformer(dfs, cbs=[
                            LowerStripNameCB(col_src='nuclide', col_dst='NUCLIDE'),
                            RemapCB(lut=lut_nuclides, col_remap='NUCLIDE', col_src='NUCLIDE'),
                            ParseTimeCB(),
                            EncodeTimeCB(),
                            SplitSedimentValuesCB(coi_sediment),
                            SanitizeValueCB(coi_val),       
                            NormalizeUncCB(),
                            RemapUnitCB(),
                            RemapDetectionLimitCB(coi_dl),                           
                            RemapCB(fn_lut=lut_biota, col_remap='SPECIES', col_src='rubin', dest_grps='BIOTA'),
                            RemapCB(fn_lut=lut_tissues, col_remap='BODY_PART', col_src='tissue', dest_grps='BIOTA'),
                            RemapCB(fn_lut=lut_biogroup_from_biota, col_remap='BIO_GROUP', col_src='SPECIES', dest_grps='BIOTA'),
                            RemapSedimentCB(fn_lut=lut_sediments, replace_lut=sed_replace_lut),
                            RemapFiltCB(lut_filtered),
                            AddSampleIDCB(),
                            AddDepthCB(),
                            AddSalinityCB(),
                            AddTemperatureCB(),
                            RemapSedSliceTopBottomCB(),
                            LookupDryWetPercentWeightCB(),
                            ParseCoordinatesCB(ddmm_to_dd),
                            SanitizeLonLatCB(),
                            AddStationCB()
                            ])
    tfm()
    encoder = NetCDFEncoder(tfm.dfs, 
                            dest_fname=fname_out, 
                            global_attrs=get_attrs(tfm, zotero_key=zotero_key, kw=kw),
                            # custom_maps=tfm.custom_maps,
                            verbose=kwargs.get('verbose', False),
                           )
    encoder.encode()

In [ ]:
#|eval: false
encode(fname_out, verbose=False)

Warning: 8 missing time value(s) in SEAWATER
Warning: 1 missing time value(s) in SEDIMENT

## NetCDF Review

First lets review the global attributes of the NetCDF file:

In [ ]:
#| eval: false
contents = ExtractNetcdfContents(fname_out)
print(contents.global_attrs)

{'id': '26VMZZ2Q', 'title': 'Environmental database - Helsinki Commission Monitoring of Radioactive Substances', 'summary': 'MORS Environment database has been used to collate data resulting from monitoring of environmental radioactivity in the Baltic Sea based on HELCOM Recommendation 26/3.\n\nThe database is structured according to HELCOM Guidelines on Monitoring of Radioactive Substances (https://www.helcom.fi/wp-content/uploads/2019/08/Guidelines-for-Monitoring-of-Radioactive-Substances.pdf), which specifies reporting format, database structure, data types and obligatory parameters used for reporting data under Recommendation 26/3.\n\nThe database is updated and quality assured annually by HELCOM MORS EG.', 'keywords': 'oceanography, Earth Science > Oceans > Ocean Chemistry> Radionuclides, Earth Science > Human Dimensions > Environmental Impacts > Nuclear Radiation Exposure, Earth Science > Oceans > Ocean Chemistry > Ocean Tracers, Earth Science > Oceans > Marine Sediments, Earth Science > Oceans > Ocean Chemistry, Earth Science > Oceans > Sea Ice > Isotopes, Earth Science > Oceans > Water Quality > Ocean Contaminants, Earth Science > Biological Classification > Animals/Vertebrates > Fish, Earth Science > Biosphere > Ecosystems > Marine Ecosystems, Earth Science > Biological Classification > Animals/Invertebrates > Mollusks, Earth Science > Biological Classification > Animals/Invertebrates > Arthropods > Crustaceans, Earth Science > Biological Classification > Plants > Macroalgae (Seaweeds)', 'history': 'TBD', 'keywords_vocabulary': 'GCMD Science Keywords', 'keywords_vocabulary_url': 'https://gcmd.earthdata.nasa.gov/static/kms/', 'record': 'TBD', 'featureType': 'TBD', 'cdm_data_type': 'TBD', 'Conventions': 'CF-1.10 ACDD-1.3', 'publisher_name': 'Paul MCGINNITY, Iolanda OSVATH, Florence DESCROIX-COMANDUCCI', 'publisher_email': 'p.mc-ginnity@iaea.org, i.osvath@iaea.org, F.Descroix-Comanducci@iaea.org', 'publisher_url': 'https://maris.iaea.org', 'publisher_institution': 'International Atomic Energy Agency - IAEA', 'creator_name': '[{"creatorType": "author", "name": "HELCOM MORS"}]', 'institution': 'TBD', 'metadata_link': 'TBD', 'creator_email': 'TBD', 'creator_url': 'TBD', 'references': 'TBD', 'license': 'Without prejudice to the applicable Terms and Conditions (https://nucleus.iaea.org/Pages/Others/Disclaimer.aspx), I hereby agree that any use of the data will contain appropriate acknowledgement of the data source(s) and the IAEA Marine Radioactivity Information System (MARIS).', 'comment': 'TBD', 'geospatial_lat_min': '31.17', 'geospatial_lon_min': '9.6333', 'geospatial_lat_max': '65.75', 'geospatial_lon_max': '53.5', 'geospatial_vertical_min': '0.0', 'geospatial_vertical_max': '437.0', 'geospatial_bounds': 'POLYGON ((9.6333 53.5, 31.17 53.5, 31.17 65.75, 9.6333 65.75, 9.6333 53.5))', 'geospatial_bounds_crs': 'EPSG:4326', 'time_coverage_start': '1984-01-10T00:00:00', 'time_coverage_end': '2023-11-30T00:00:00', 'local_time_zone': 'TBD', 'date_created': 'TBD', 'date_modified': 'TBD', 'publisher_postprocess_logs': "Convert 'nuclide' column values to lowercase, strip spaces, and store in 'NUCLIDE' column., Remap data provider nuclide names to standardized MARIS nuclide names., Standardize time format across all dataframes., Encode time as seconds since epoch., Separate sediment entries into distinct rows for Bq/kg and Bq/m² measurements., Sanitize measurement values by removing blanks and standardizing to use the `VALUE` column., Convert from relative error to standard uncertainty., Set the `unit` id column in the DataFrames based on a lookup table., Remap values from 'rubin' to 'SPECIES' for groups: BIOTA., Remap values from 'tissue' to 'BODY_PART' for groups: BIOTA., Remap values from 'SPECIES' to 'BIO_GROUP' for groups: BIOTA., Lookup sediment id using lookup table., Lookup filt value in dataframe using the lookup table., Generate a SMP_ID from the KEY values in the HELCOM dataset., Ensure depth values are floats and add 'SMP_DEPTH' and 'TOT_DEPTH' columns., Remap Sediment slice top and bottom to MARIS format., Lookup dry-wet ratio and format for MARIS., Get geographical coordinates from columns expressed in degrees decimal format or from columns in degrees/minutes decimal format where degrees decimal format is missing or zero., Drop rows with invalid longitude & latitude values. Convert `,` separator to `.` separator., Add station to all DataFrames."}

Review the publisher_postprocess_logs.

In [ ]:
#| eval: false
print(contents.global_attrs['publisher_postprocess_logs'])

Convert 'nuclide' column values to lowercase, strip spaces, and store in 'NUCLIDE' column., Remap data provider nuclide names to standardized MARIS nuclide names., Standardize time format across all dataframes., Encode time as seconds since epoch., Separate sediment entries into distinct rows for Bq/kg and Bq/m² measurements., Sanitize measurement values by removing blanks and standardizing to use the `VALUE` column., Convert from relative error to standard uncertainty., Set the `unit` id column in the DataFrames based on a lookup table., Remap values from 'rubin' to 'SPECIES' for groups: BIOTA., Remap values from 'tissue' to 'BODY_PART' for groups: BIOTA., Remap values from 'SPECIES' to 'BIO_GROUP' for groups: BIOTA., Lookup sediment id using lookup table., Lookup filt value in dataframe using the lookup table., Generate a SMP_ID from the KEY values in the HELCOM dataset., Ensure depth values are floats and add 'SMP_DEPTH' and 'TOT_DEPTH' columns., Remap Sediment slice top and bottom to MARIS format., Lookup dry-wet ratio and format for MARIS., Get geographical coordinates from columns expressed in degrees decimal format or from columns in degrees/minutes decimal format where degrees decimal format is missing or zero., Drop rows with invalid longitude & latitude values. Convert `,` separator to `.` separator., Add station to all DataFrames.

Now lets review the enums of the groups in the NetCDF file:

In [ ]:
#| eval: false
print('Example of enum_dicts:')
print(contents.enum_dicts['BIOTA']['bio_group'])

Example of enum_dicts:
{'Not applicable': '-1', 'Not available': '0', 'Birds': '1', 'Crustaceans': '2', 'Echinoderms': '3', 'Fish': '4', 'Mammals': '5', 'Molluscs': '6', 'Others': '7', 'Plankton': '8', 'Polychaete worms': '9', 'Reptile': '10', 'Seaweeds and plants': '11', 'Cephalopods': '12', 'Gastropods': '13', 'Bivalves': '14'}

Lets return the data contained in the NetCDF file:

In [ ]:
#| eval: false
dfs = contents.dfs

Lets review the biota data:

In [ ]:
#| eval: false
nc_dfs_biota=dfs['BIOTA']
with pd.option_context('display.max_columns', None):
    display(nc_dfs_biota)

,SMP_ID_PROVIDER,LON,LAT,SMP_DEPTH,TIME,STATION,SMP_ID,NUCLIDE,VALUE,UNIT,UNC,DL,BIO_GROUP,SPECIES,BODY_PART,DRYWT,WETWT,PERCENTWT
0,BVTIG2012041,12.316667,54.283333,NaN,1348358400,SD24,1,31,0.010140,5,NaN,2,4,99,52,174.934433,948.0,0.18453
1,BVTIG2012041,12.316667,54.283333,NaN,1348358400,SD24,2,4,135.300003,5,4.830210,1,4,99,52,174.934433,948.0,0.18453
2,BVTIG2012041,12.316667,54.283333,NaN,1348358400,SD24,3,9,0.013980,5,NaN,2,4,99,52,174.934433,948.0,0.18453
3,BVTIG2012041,12.316667,54.283333,NaN,1348358400,SD24,4,33,4.338000,5,0.150962,1,4,99,52,174.934433,948.0,0.18453
4,BVTIG2012040,12.316667,54.283333,NaN,1348358400,SD24,5,31,0.009614,5,NaN,2,4,99,52,177.935120,964.0,0.18458
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16089,BSTUK2022010,21.395000,61.241501,2.0,1652140800,OLKB,16090,33,13.700000,4,0.520600,1,11,96,55,NaN,NaN,NaN
16090,BSTUK2022010,21.395000,61.241501,2.0,1652140800,OLKB,16091,9,0.500000,4,0.045500,1,11,96,55,NaN,NaN,NaN
16091,BSTUK2022011,21.385000,61.343334,NaN,1663200000,OLKC,16092,4,50.700001,4,4.106700,1,14,129,1,NaN,NaN,NaN
16092,BSTUK2022011,21.385000,61.343334,NaN,1663200000,OLKC,16093,33,0.880000,4,0.140800,1,14,129,1,NaN,NaN,NaN
16093,BSTUK2022011,21.385000,61.343334,NaN,1663200000,OLKC,16094,12,6.600000,4,0.349800,1,14,129,1,NaN,NaN,NaN

Lets review the sediment data:

In [ ]:
#| eval: false
nc_dfs_sediment = dfs['SEDIMENT']
with pd.option_context('display.max_columns', None):
    display(nc_dfs_sediment)

,SMP_ID_PROVIDER,LON,LAT,TOT_DEPTH,TIME,STATION,SMP_ID,NUCLIDE,VALUE,UNIT,UNC,DL,SED_TYPE,TOP,BOTTOM,PERCENTWT
0,SKRIL2012116,27.799999,60.466667,25.0,1337904000,RU99,1,33,1200.000000,3,240.000000,1,0,15.0,20.0,NaN
1,SKRIL2012117,27.799999,60.466667,25.0,1337904000,RU99,2,33,250.000000,3,50.000000,1,0,20.0,25.0,NaN
2,SKRIL2012118,27.799999,60.466667,25.0,1337904000,RU99,3,33,140.000000,3,29.400000,1,0,25.0,30.0,NaN
3,SKRIL2012119,27.799999,60.466667,25.0,1337904000,RU99,4,33,79.000000,3,15.800000,1,0,30.0,35.0,NaN
4,SKRIL2012120,27.799999,60.466667,25.0,1337904000,RU99,5,33,29.000000,3,6.960000,1,0,35.0,40.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70444,SCLOR2022071,15.537800,54.617832,62.0,1654646400,P39Z,70445,67,0.044000,2,0.015312,1,10,15.0,17.0,0.257642
70445,SCLOR2022071,15.537800,54.617832,62.0,1654646400,P39Z,70446,77,2.500000,2,0.185000,1,10,15.0,17.0,0.257642
70446,SCLOR2022072,15.537800,54.617832,62.0,1654646400,P39Z,70447,4,5873.000000,2,164.444000,1,10,17.0,19.0,0.263965
70447,SCLOR2022072,15.537800,54.617832,62.0,1654646400,P39Z,70448,33,21.200001,2,2.162400,1,10,17.0,19.0,0.263965
70448,SCLOR2022072,15.537800,54.617832,62.0,1654646400,P39Z,70449,77,0.370000,2,0.048100,1,10,17.0,19.0,0.263965

Lets review the seawater data:

In [ ]:
#| eval: false
nc_dfs_seawater = dfs['SEAWATER']
with pd.option_context('display.max_columns', None):
    display(nc_dfs_seawater)

,SMP_ID_PROVIDER,LON,LAT,SMP_DEPTH,TOT_DEPTH,TIME,STATION,SMP_ID,NUCLIDE,VALUE,UNIT,UNC,DL,FILT,SAL,TEMP
0,WKRIL2012003,29.333300,60.083302,0.0,NaN,1337731200,RU10,1,33,5.300000,1,1.696000,1,0,NaN,NaN
1,WKRIL2012004,29.333300,60.083302,29.0,NaN,1337731200,RU10,2,33,19.900000,1,3.980000,1,0,NaN,NaN
2,WKRIL2012005,23.150000,59.433300,0.0,NaN,1339891200,RU11,3,33,25.500000,1,5.100000,1,0,NaN,NaN
3,WKRIL2012006,27.983299,60.250000,0.0,NaN,1337817600,RU19,4,33,17.000000,1,4.930000,1,0,NaN,NaN
4,WKRIL2012007,27.983299,60.250000,39.0,NaN,1337817600,RU19,5,33,22.200001,1,3.996000,1,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21468,WDHIG2023112,13.499833,54.600334,0.0,47.0,1686441600,WITTOW,21469,1,702.838074,1,51.276207,1,0,7.89,NaN
21469,WDHIG2023113,13.499833,54.600334,45.0,47.0,1686441600,WITTOW,21470,1,725.855713,1,52.686260,1,0,14.80,NaN
21470,WDHIG2023143,14.200833,54.600334,0.0,11.0,1686614400,ODER,21471,1,648.992920,1,48.154419,1,0,5.70,NaN
21471,WDHIG2023145,14.665500,54.600334,0.0,20.0,1686614400,OBANK,21472,1,627.178406,1,46.245316,1,0,7.76,NaN
21472,WDHIG2023147,14.330000,54.600334,0.0,17.0,1686614400,ADLERG,21473,1,605.715088,1,45.691143,1,0,7.67,NaN

## Data Format Conversion 

The MARIS data processing workflow involves two key steps:

1. **NetCDF to Standardized CSV Compatible with OpenRefine Pipeline**
   - Convert standardized NetCDF files to CSV formats compatible with OpenRefine using the `NetCDFDecoder`.
   - Preserve data integrity and variable relationships.
   - Maintain standardized nomenclature and units.

2. **Database Integration**
   - Process the converted CSV files using OpenRefine.
   - Apply data cleaning and standardization rules.
   - Export validated data to the MARIS master database.

This section focuses on the first step: converting NetCDF files to a format suitable for OpenRefine processing using the `NetCDFDecoder` class.

In [ ]:
#|eval: false
decode(fname_in=fname_out, verbose=True)

Saved BIOTA to ../../_data/output/100-HELCOM-MORS-2024_BIOTA.csv
Saved SEAWATER to ../../_data/output/100-HELCOM-MORS-2024_SEAWATER.csv
Saved SEDIMENT to ../../_data/output/100-HELCOM-MORS-2024_SEDIMENT.csv